#!/usr/bin/env perl
# --
# SPDX-License-Identifier: GPL-3.0-only
# --
use v5.24;use strict;use warnings;use lib '/opt/careoncloud';use lib '/opt/careoncloud/Kernel/cpan-lib';use Kernel::System::ObjectManager;
local$Kernel::OM=Kernel::System::ObjectManager->new('Kernel::System::Log'=>{LogPrefix=>'CareOnCloud-problem-demo'});my$UserID=47;my$Directory=$Kernel::OM->Get('Kernel::System::D724::TenantDirectory');my$Problem=$Kernel::OM->Get('Kernel::System::D724::Problem');my$Ctx=$Directory->ContextGet(UserID=>$UserID);die"User context unavailable\n"if!$Ctx->{Success};my$Subject=$Ctx->{Subject};my%Allowed=map{$_=>1}@{$Subject->{TenantIDs}};
my@Seed=(
 ['showcase-bank','Mobil bankacilik oturum zaman asimi artisi','application','critical','high','known_error','Kimlik servisi baglanti havuzu kampanya saatlerinde tuketiliyor.','Etkilenen worker grubunu kontrollu yeniden baslat.','Havuz sinirlarini talep bazli ayir ve doygunluk korumasi ekle.'],
 ['showcase-bank','ATM mutabakat dosyalarinda gecikme','process','high','medium','investigating','Dosya siralama zamanlayicilarinda cakisma arastiriliyor.','Geciken dosyalari kontrollu manuel kuyruga al.',q{}],
 ['showcase-retail','Magaza POS fiyat sorgusu yavasligi','capacity','high','high','resolved','Kampanya onbellegi tek bolumde sicak anahtar olusturuyor.','Magazalari bolgesel onbellek grubuna yonlendir.','Onbellegi bolgesel parcala ve sicak anahtar korumasi ekle.'],
 ['showcase-retail','Depo el terminali baglanti kopmalari','network','medium','high','known_error','Kablosuz denetleyici roaming esigi depo raflarinda yuksek kaliyor.','Terminal profilinde roaming esigini gecici dusur.','Depo RF olcumuyle erisim noktasi ve esik tasarimini yenile.'],
 ['showcase-fashion','Kampanya sepet fiyat farki','application','critical','critical','known_error','Fiyat kurali surumleri uygulama dugumlerinde farkli zamanda etkinlesiyor.','Fiyat dugumlerini ayni kural surumune sabitle.','Kural yayinini atomik surum gecidine tasi.'],
 ['showcase-fashion','Magaza stok gorunurlugu gecikmesi','supplier','medium','medium','draft',q{},q{},q{}],
);
my($Created,$Existing)=(0,0);for my$S(@Seed){my($Tenant,$Title,$Category,$Impact,$Urgency,$Target,$Cause,$Workaround,$Fix)=@$S;next if!$Allowed{$Tenant};my$L=$Problem->List(Subject=>$Subject,TenantID=>$Tenant,UserID=>$UserID);die"List failed: $L->{Error}\n"if!$L->{Success};if(grep{$_->{Title}eq$Title}@{$L->{Data}}){$Existing++;next}my$R=$Problem->Create(Subject=>$Subject,TenantID=>$Tenant,UserID=>$UserID,Title=>$Title,Symptom=>"CareOnCloud demo tekrarlayan belirti: $Title",BusinessImpact=>'Hizmet kalitesi, musteri deneyimi ve operasyonel verimlilik etkileniyor.',Category=>$Category,Impact=>$Impact,Urgency=>$Urgency);die"Create failed: $R->{Error}\n"if!$R->{Success};my($ID,$V)=@{$R->{Data}}{qw(ProblemID Version)};if($Target ne'draft'){$R=$Problem->Start(Subject=>$Subject,TenantID=>$Tenant,UserID=>$UserID,ProblemID=>$ID,ExpectedVersion=>$V);die"Start failed: $R->{Error}\n"if!$R->{Success};$V=$R->{Data}->{Version}}if($Target=~m{\A(?:known_error|resolved|closed)\z}){$R=$Problem->Diagnose(Subject=>$Subject,TenantID=>$Tenant,UserID=>$UserID,ProblemID=>$ID,ExpectedVersion=>$V,RootCause=>$Cause,Workaround=>$Workaround);die"Diagnose failed: $R->{Error}\n"if!$R->{Success};$V=$R->{Data}->{Version}}if($Target eq'known_error'){$R=$Problem->PublishKnownError(Subject=>$Subject,TenantID=>$Tenant,UserID=>$UserID,ProblemID=>$ID,ExpectedVersion=>$V);die"Known error failed: $R->{Error}\n"if!$R->{Success}}elsif($Target=~m{\A(?:resolved|closed)\z}){$R=$Problem->Resolve(Subject=>$Subject,TenantID=>$Tenant,UserID=>$UserID,ProblemID=>$ID,ExpectedVersion=>$V,PermanentFix=>$Fix);die"Resolve failed: $R->{Error}\n"if!$R->{Success};$V=$R->{Data}->{Version};if($Target eq'closed'){$R=$Problem->Close(Subject=>$Subject,TenantID=>$Tenant,UserID=>$UserID,ProblemID=>$ID,ExpectedVersion=>$V);die"Close failed: $R->{Error}\n"if!$R->{Success}}}$Created++}print"CareOnCloud Problem demo seed complete: created=$Created existing=$Existing\n";
