# --
# CareOnCloud ESM enterprise service management platform.
# SPDX-License-Identifier: GPL-3.0-only
# --
package Kernel::System::CareOnCloud::CMDB;
use v5.24;use strict;use warnings;
our $VERSION='0.4.1';
our @ObjectDependencies=('Kernel::Config','Kernel::System::CareOnCloud::Audit','Kernel::System::CareOnCloud::TenantGuard','Kernel::System::DB','Kernel::System::JSON');
my%TypeStatus=map{$_=>1}qw(draft active retired);my%CIStatus=map{$_=>1}qw(planned active maintenance retired);my%Criticality=map{$_=>1}qw(low medium high critical);my%RelationType=map{$_=>1}qw(depends_on runs_on connects_to contains backs_up);my%BindingType=map{$_=>1}qw(supported_by depends_on);my%FieldType=map{$_=>1}qw(text number boolean date datetime ip hostname url select);
my%ServiceModel=map{$_=>1}qw(fixed_scope unify_pack project);
sub new{return bless{},$_[0]}

sub CategoryCreate{my($S,%P)=@_;return$S->_TransactionRun(Code=>sub{my$A=$S->_Auth(Action=>'cmdb.manage',RequireUserID=>1,%P);return$A if!$A->{Success};$P{Description}//=q{};$P{Status}//='draft';my$V=$S->_BaseValidate(%P,StatusSet=>\%TypeStatus);return$V if!$V->{Success};return$S->_Error('KEY_EXISTS')if$S->_CategoryByKey(%P);my@V=(@P{qw(TenantID Key Name Description Status)},$P{UserID},$P{UserID});my@B=map{\$_}@V;$Kernel::OM->Get('Kernel::System::DB')->Do(SQL=>'INSERT INTO careoncloud_service_category (tenant_id,key_name,name,description,status,version,create_time,create_by,change_time,change_by) VALUES (?,?,?,?,?,1,current_timestamp,?,current_timestamp,?)',Bind=>\@B)||return$S->_Error('DATABASE_ERROR');my$R=$S->_CategoryByKey(%P);$S->_Audit(%P,Action=>'cmdb.category.created',ObjectType=>'service_category',ObjectID=>$R->{CategoryID},Version=>1,From=>q{},To=>$R->{Status},Details=>{key=>$R->{Key},name=>$R->{Name}});return{Success=>1,Data=>$R}})}
sub CategoryGet{my($S,%P)=@_;my$A=$S->_Auth(Action=>'cmdb.read',%P);return$A if!$A->{Success};return$S->_Error('ID_INVALID')if!$S->_ID($P{CategoryID});my$R=$S->_CategoryRow(%P);return$R?{Success=>1,Data=>$R}:$S->_Error('NOT_FOUND')}
sub CategoryList{my($S,%P)=@_;my$A=$S->_Auth(Action=>'cmdb.read',%P);return$A if!$A->{Success};my$T=$P{TenantID};my$DB=$Kernel::OM->Get('Kernel::System::DB');$DB->Prepare(SQL=>'SELECT id,tenant_id,key_name,name,description,status,version,create_time,change_time FROM careoncloud_service_category WHERE tenant_id=? ORDER BY name,id',Bind=>[\$T],Limit=>$Kernel::OM->Get('Kernel::Config')->Get('CareOnCloud::CMDB::ListLimit')//200);my@D;while(my@R=$DB->FetchrowArray()){push@D,$S->_CategoryMap(\@R)}return{Success=>1,Data=>\@D}}
sub CategoryUpdate{my($S,%P)=@_;return$S->_TransactionRun(Code=>sub{my$A=$S->_Auth(Action=>'cmdb.manage',RequireUserID=>1,%P);return$A if!$A->{Success};return$S->_Error('VERSION_REQUIRED')if!$S->_ID($P{ExpectedVersion});my$C=$S->_CategoryRow(%P);return$S->_Error('NOT_FOUND')if!$C;return$S->_Error('VERSION_CONFLICT')if$C->{Version}!=$P{ExpectedVersion};return$S->_Error('IMMUTABLE_KEY')if defined$P{Key}&&$P{Key}ne$C->{Key};for(qw(Name Description Status)){$P{$_}=$C->{$_}if!defined$P{$_}}my$V=$S->_BaseValidate(%P,Key=>$C->{Key},StatusSet=>\%TypeStatus);return$V if!$V->{Success};my@V=(@P{qw(Name Description Status UserID TenantID CategoryID ExpectedVersion)});my@B=map{\$_}@V;$Kernel::OM->Get('Kernel::System::DB')->Do(SQL=>'UPDATE careoncloud_service_category SET name=?,description=?,status=?,version=version+1,change_time=current_timestamp,change_by=? WHERE tenant_id=? AND id=? AND version=?',Bind=>\@B)||return$S->_Error('DATABASE_ERROR');my$R=$S->_CategoryRow(%P);my$N=$C->{Version}+1;return$S->_Error('VERSION_CONFLICT')if!$R||$R->{Version}!=$N;$S->_Audit(%P,Action=>'cmdb.category.updated',ObjectType=>'service_category',ObjectID=>$P{CategoryID},Version=>$N,From=>$C->{Status},To=>$R->{Status},Details=>{key=>$R->{Key},name=>$R->{Name}});return{Success=>1,Data=>$R}})}
sub TenantLabelGet{my($S,%P)=@_;my$A=$S->_Auth(Action=>'cmdb.read',%P);return$A if!$A->{Success};my$T=$P{TenantID};my$Active='active';my$DB=$Kernel::OM->Get('Kernel::System::DB');$DB->Prepare(SQL=>'SELECT name FROM careoncloud_tenant WHERE key_name=? AND status=?',Bind=>[\$T,\$Active],Limit=>1);my($N)=$DB->FetchrowArray();return defined$N?{Success=>1,Data=>{TenantID=>$T,Name=>$N}}:$S->_Error('NOT_FOUND')}
sub ServiceCategorize{my($S,%P)=@_;return$S->_TransactionRun(Code=>sub{my$A=$S->_Auth(Action=>'cmdb.manage',RequireUserID=>1,%P);return$A if!$A->{Success};return$S->_Error('ID_INVALID')if!$S->_ID($P{CategoryID})||!$S->_ID($P{ServiceID});return$S->_Error('CATEGORY_NOT_FOUND')if!$S->_CategoryRow(%P);return$S->_Error('SERVICE_NOT_FOUND')if!$S->_ServiceExists(%P);my$T=$P{TenantID};my$SID=$P{ServiceID};my$DB=$Kernel::OM->Get('Kernel::System::DB');$DB->Prepare(SQL=>'SELECT id,category_id,version FROM careoncloud_service_category_service WHERE tenant_id=? AND service_id=? FOR UPDATE',Bind=>[\$T,\$SID]);my($ID,$Old,$Ver)=$DB->FetchrowArray();return{Success=>1,Data=>{CategoryServiceID=>0+$ID,TenantID=>$T,CategoryID=>0+$Old,ServiceID=>0+$SID,Version=>0+$Ver},IdempotentReplay=>1}if$ID&&$Old==$P{CategoryID};my$N=1;if($ID){$N=$Ver+1;my@V=($P{CategoryID},$P{UserID},$T,$ID,$Ver);my@B=map{\$_}@V;$DB->Do(SQL=>'UPDATE careoncloud_service_category_service SET category_id=?,version=version+1,change_time=current_timestamp,change_by=? WHERE tenant_id=? AND id=? AND version=?',Bind=>\@B)||return$S->_Error('DATABASE_ERROR')}else{my@V=($T,$P{CategoryID},$SID,$P{UserID},$P{UserID});my@B=map{\$_}@V;$DB->Do(SQL=>'INSERT INTO careoncloud_service_category_service (tenant_id,category_id,service_id,version,create_time,create_by,change_time,change_by) VALUES (?,?,?,1,current_timestamp,?,current_timestamp,?)',Bind=>\@B)||return$S->_Error('DATABASE_ERROR');$DB->Prepare(SQL=>'SELECT id FROM careoncloud_service_category_service WHERE tenant_id=? AND service_id=?',Bind=>[\$T,\$SID],Limit=>1);($ID)=$DB->FetchrowArray()}$S->_Audit(%P,Action=>'cmdb.service.categorized',ObjectType=>'service_category_link',ObjectID=>$ID,Version=>$N,From=>defined$Old?"$Old":q{},To=>"$P{CategoryID}",Details=>{service_id=>$SID,category_id=>$P{CategoryID}});return{Success=>1,Data=>{CategoryServiceID=>0+$ID,TenantID=>$T,CategoryID=>0+$P{CategoryID},ServiceID=>0+$SID,Version=>$N}}})}

sub InstanceCreate{my($S,%P)=@_;return$S->_TransactionRun(Code=>sub{my$A=$S->_Auth(Action=>'cmdb.manage',RequireUserID=>1,%P);return$A if!$A->{Success};$P{Description}//=q{};$P{Status}//='active';$P{Criticality}//='medium';$P{ServiceModel}//='fixed_scope';my$V=$S->_BaseValidate(%P,StatusSet=>\%CIStatus);return$V if!$V->{Success};return$S->_Error('ID_INVALID')if!$S->_ID($P{ServiceID});return$S->_Error('SERVICE_NOT_FOUND')if!$S->_ServiceExists(%P);return$S->_Error('CRITICALITY_INVALID')if!$Criticality{$P{Criticality}};return$S->_Error('SERVICE_MODEL_INVALID')if!$ServiceModel{$P{ServiceModel}};return$S->_Error('SUPPORT_GROUP_NOT_FOUND')if defined$P{SupportGroupID}&&!$S->_GroupExists($P{SupportGroupID});return$S->_Error('KEY_EXISTS')if$S->_InstanceByKey(%P);my@V=(@P{qw(TenantID ServiceID Key Name Description SupportGroupID ServiceModel Status Criticality)},$P{UserID},$P{UserID});my@B=map{\$_}@V;$Kernel::OM->Get('Kernel::System::DB')->Do(SQL=>'INSERT INTO careoncloud_service_instance (tenant_id,service_id,key_name,name,description,support_group_id,service_model,status,criticality,version,create_time,create_by,change_time,change_by) VALUES (?,?,?,?,?,?,?,?,?,1,current_timestamp,?,current_timestamp,?)',Bind=>\@B)||return$S->_Error('DATABASE_ERROR');my$R=$S->_InstanceByKey(%P);$S->_Audit(%P,Action=>'cmdb.service_instance.created',ObjectType=>'service_instance',ObjectID=>$R->{ServiceInstanceID},Version=>1,From=>q{},To=>$R->{Status},Details=>{service_id=>$R->{ServiceID},support_group_id=>$R->{SupportGroupID}//q{},service_model=>$R->{ServiceModel}});return{Success=>1,Data=>$R}})}
sub InstanceGet{my($S,%P)=@_;my$A=$S->_Auth(Action=>'cmdb.read',%P);return$A if!$A->{Success};return$S->_Error('ID_INVALID')if!$S->_ID($P{ServiceInstanceID});my$R=$S->_InstanceRow(%P);return$R?{Success=>1,Data=>$R}:$S->_Error('NOT_FOUND')}
sub InstanceList{my($S,%P)=@_;my$A=$S->_Auth(Action=>'cmdb.read',%P);return$A if!$A->{Success};my$T=$P{TenantID};my@V=($T);my$W='tenant_id=?';if(defined$P{ServiceID}){return$S->_Error('ID_INVALID')if!$S->_ID($P{ServiceID});$W.=' AND service_id=?';push@V,$P{ServiceID}}my@B=map{\$_}@V;my$DB=$Kernel::OM->Get('Kernel::System::DB');$DB->Prepare(SQL=>"SELECT id,tenant_id,service_id,key_name,name,description,support_group_id,service_model,status,criticality,version,create_time,change_time FROM careoncloud_service_instance WHERE $W ORDER BY service_id,name,id",Bind=>\@B,Limit=>$Kernel::OM->Get('Kernel::Config')->Get('CareOnCloud::CMDB::ListLimit')//200);my@D;while(my@R=$DB->FetchrowArray()){push@D,$S->_InstanceMap(\@R)}return{Success=>1,Data=>\@D}}
sub InstanceUpdate{my($S,%P)=@_;return$S->_TransactionRun(Code=>sub{my$A=$S->_Auth(Action=>'cmdb.manage',RequireUserID=>1,%P);return$A if!$A->{Success};return$S->_Error('VERSION_REQUIRED')if!$S->_ID($P{ExpectedVersion});my$C=$S->_InstanceRow(%P);return$S->_Error('NOT_FOUND')if!$C;return$S->_Error('VERSION_CONFLICT')if$C->{Version}!=$P{ExpectedVersion};return$S->_Error('IMMUTABLE_KEY')if defined$P{Key}&&$P{Key}ne$C->{Key};return$S->_Error('IMMUTABLE_SERVICE')if defined$P{ServiceID}&&$P{ServiceID}!=$C->{ServiceID};for(qw(Name Description SupportGroupID ServiceModel Status Criticality)){$P{$_}=$C->{$_}if!exists$P{$_}}my$V=$S->_BaseValidate(%P,Key=>$C->{Key},StatusSet=>\%CIStatus);return$V if!$V->{Success};return$S->_Error('CRITICALITY_INVALID')if!$Criticality{$P{Criticality}};return$S->_Error('SERVICE_MODEL_INVALID')if!$ServiceModel{$P{ServiceModel}};return$S->_Error('SUPPORT_GROUP_NOT_FOUND')if defined$P{SupportGroupID}&&!$S->_GroupExists($P{SupportGroupID});my@V=(@P{qw(Name Description SupportGroupID ServiceModel Status Criticality UserID TenantID ServiceInstanceID ExpectedVersion)});my@B=map{\$_}@V;$Kernel::OM->Get('Kernel::System::DB')->Do(SQL=>'UPDATE careoncloud_service_instance SET name=?,description=?,support_group_id=?,service_model=?,status=?,criticality=?,version=version+1,change_time=current_timestamp,change_by=? WHERE tenant_id=? AND id=? AND version=?',Bind=>\@B)||return$S->_Error('DATABASE_ERROR');my$R=$S->_InstanceRow(%P);my$N=$C->{Version}+1;return$S->_Error('VERSION_CONFLICT')if!$R||$R->{Version}!=$N;$S->_Audit(%P,Action=>'cmdb.service_instance.updated',ObjectType=>'service_instance',ObjectID=>$P{ServiceInstanceID},Version=>$N,From=>$C->{Status},To=>$R->{Status},Details=>{service_id=>$C->{ServiceID},support_group_id=>$R->{SupportGroupID}//q{},service_model=>$R->{ServiceModel}});return{Success=>1,Data=>$R}})}

sub TypeCreate{my($S,%P)=@_;return$S->_TransactionRun(Code=>sub{$S->_TypeCreate(%P)})}
sub TypeGet{my($S,%P)=@_;my$A=$S->_Auth(Action=>'cmdb.read',%P);return$A if!$A->{Success};return$S->_Error('ID_INVALID')if!$S->_ID($P{TypeID});my$R=$S->_TypeRow(TenantID=>$P{TenantID},TypeID=>$P{TypeID});return$R?{Success=>1,Data=>$R}:$S->_Error('NOT_FOUND')}
sub TypeList{my($S,%P)=@_;return$S->_List(Entity=>'type',%P)}
sub TypeUpdate{my($S,%P)=@_;return$S->_TransactionRun(Code=>sub{$S->_TypeUpdate(%P)})}
sub CICreate{my($S,%P)=@_;return$S->_TransactionRun(Code=>sub{$S->_CICreate(%P)})}
sub CIGet{my($S,%P)=@_;my$A=$S->_Auth(Action=>'cmdb.read',%P);return$A if!$A->{Success};return$S->_Error('ID_INVALID')if!$S->_ID($P{CIID});my$R=$S->_CIRow(TenantID=>$P{TenantID},CIID=>$P{CIID});return$R?{Success=>1,Data=>$R}:$S->_Error('NOT_FOUND')}
sub CIList{my($S,%P)=@_;return$S->_List(Entity=>'ci',%P)}
sub CIUpdate{my($S,%P)=@_;return$S->_TransactionRun(Code=>sub{$S->_CIUpdate(%P)})}

sub _TypeCreate{
 my($S,%P)=@_;my$A=$S->_Auth(Action=>'cmdb.manage',RequireUserID=>1,%P);return$A if!$A->{Success};$P{Description}//=q{};$P{Status}//='draft';my$V=$S->_BaseValidate(%P,StatusSet=>\%TypeStatus);return$V if!$V->{Success};my$Schema=$S->_SchemaValidate($P{AttributeSchema});return$Schema if!$Schema->{Success};return$S->_Error('KEY_EXISTS')if$S->_TypeByKey(%P);
 my$J=$S->_JSON($Schema->{Data});my@V=(@P{qw(TenantID Key Name Description Status)},$J,$P{UserID},$P{UserID});my@B=map{\$_}@V;return$S->_Error('DATABASE_ERROR')if!$Kernel::OM->Get('Kernel::System::DB')->Do(SQL=>'INSERT INTO careoncloud_ci_type (tenant_id,key_name,name,description,status,attribute_schema_json,version,create_time,create_by,change_time,change_by) VALUES (?,?,?,?,?,?,1,current_timestamp,?,current_timestamp,?)',Bind=>\@B);my$R=$S->_TypeByKey(%P);return$S->_Error('DATABASE_ERROR')if!$R;$S->_Audit(%P,Action=>'cmdb.type.created',ObjectType=>'ci_type',ObjectID=>$R->{TypeID},Version=>1,From=>q{},To=>$P{Status},Details=>{key=>$P{Key},name=>$P{Name}});return{Success=>1,Data=>$R}
}
sub _TypeUpdate{
 my($S,%P)=@_;my$A=$S->_Auth(Action=>'cmdb.manage',RequireUserID=>1,%P);return$A if!$A->{Success};return$S->_Error('ID_INVALID')if!$S->_ID($P{TypeID});return$S->_Error('VERSION_REQUIRED')if!$S->_ID($P{ExpectedVersion});my$C=$S->_TypeRow(%P);return$S->_Error('NOT_FOUND')if!$C;return$S->_Error('VERSION_CONFLICT')if$C->{Version}!=$P{ExpectedVersion};return$S->_Error('IMMUTABLE_KEY')if defined$P{Key}&&$P{Key}ne$C->{Key};for(qw(Name Description Status)){ $P{$_}=$C->{$_} if!defined$P{$_} }my$V=$S->_BaseValidate(%P,Key=>$C->{Key},StatusSet=>\%TypeStatus);return$V if!$V->{Success};my$Schema=defined$P{AttributeSchema}?$S->_SchemaValidate($P{AttributeSchema}):{Success=>1,Data=>$C->{AttributeSchema}};return$Schema if!$Schema->{Success};my$J=$S->_JSON($Schema->{Data});my@V=($P{Name},$P{Description},$P{Status},$J,$P{UserID},$P{TenantID},$P{TypeID},$P{ExpectedVersion});my@B=map{\$_}@V;$Kernel::OM->Get('Kernel::System::DB')->Do(SQL=>'UPDATE careoncloud_ci_type SET name=?,description=?,status=?,attribute_schema_json=?,version=version+1,change_time=current_timestamp,change_by=? WHERE tenant_id=? AND id=? AND version=?',Bind=>\@B)||return$S->_Error('DATABASE_ERROR');my$R=$S->_TypeRow(%P);my$N=$C->{Version}+1;return$S->_Error('VERSION_CONFLICT')if!$R||$R->{Version}!=$N;$S->_Audit(%P,Action=>'cmdb.type.updated',ObjectType=>'ci_type',ObjectID=>$P{TypeID},Version=>$N,From=>$C->{Status},To=>$R->{Status},Details=>{key=>$C->{Key},name=>$R->{Name}});return{Success=>1,Data=>$R}
}
sub _CICreate{
 my($S,%P)=@_;my$A=$S->_Auth(Action=>'cmdb.manage',RequireUserID=>1,%P);return$A if!$A->{Success};$P{Description}//=q{};$P{Status}//='planned';$P{Criticality}//='medium';my$V=$S->_BaseValidate(%P,StatusSet=>\%CIStatus);return$V if!$V->{Success};return$S->_Error('TYPE_ID_INVALID')if!$S->_ID($P{TypeID});return$S->_Error('CRITICALITY_INVALID')if!$Criticality{$P{Criticality}};return$S->_Error('OWNER_INVALID')if defined$P{OwnerUserID}&&!$S->_UserExists($P{OwnerUserID});my$T=$S->_TypeRow(TenantID=>$P{TenantID},TypeID=>$P{TypeID});return$S->_Error('TYPE_NOT_FOUND')if!$T||$T->{Status}ne'active';my$Attrs=$S->_AttributesValidate(Schema=>$T->{AttributeSchema},Attributes=>$P{Attributes});return$Attrs if!$Attrs->{Success};return$S->_Error('KEY_EXISTS')if$S->_CIByKey(%P);my$J=$S->_JSON($Attrs->{Data});my@V=(@P{qw(TenantID TypeID Key Name Description Status Criticality)},$P{OwnerUserID},$J,$P{UserID},$P{UserID});my@B=map{\$_}@V;$Kernel::OM->Get('Kernel::System::DB')->Do(SQL=>'INSERT INTO careoncloud_ci (tenant_id,type_id,key_name,name,description,status,criticality,owner_user_id,attributes_json,version,create_time,create_by,change_time,change_by) VALUES (?,?,?,?,?,?,?,?,?,1,current_timestamp,?,current_timestamp,?)',Bind=>\@B)||return$S->_Error('DATABASE_ERROR');my$R=$S->_CIByKey(%P);return$S->_Error('DATABASE_ERROR')if!$R;$S->_Audit(%P,Action=>'cmdb.ci.created',ObjectType=>'ci',ObjectID=>$R->{CIID},Version=>1,From=>q{},To=>$R->{Status},Details=>{key=>$P{Key},type_id=>$P{TypeID},criticality=>$P{Criticality}});return{Success=>1,Data=>$R}
}
sub _CIUpdate{
 my($S,%P)=@_;my$A=$S->_Auth(Action=>'cmdb.manage',RequireUserID=>1,%P);return$A if!$A->{Success};return$S->_Error('ID_INVALID')if!$S->_ID($P{CIID});return$S->_Error('VERSION_REQUIRED')if!$S->_ID($P{ExpectedVersion});my$C=$S->_CIRow(%P);return$S->_Error('NOT_FOUND')if!$C;return$S->_Error('VERSION_CONFLICT')if$C->{Version}!=$P{ExpectedVersion};return$S->_Error('IMMUTABLE_KEY')if defined$P{Key}&&$P{Key}ne$C->{Key};return$S->_Error('IMMUTABLE_TYPE')if defined$P{TypeID}&&$P{TypeID}!=$C->{TypeID};for(qw(Name Description Status Criticality OwnerUserID)){ $P{$_}=$C->{$_} if!exists$P{$_} }my$V=$S->_BaseValidate(%P,Key=>$C->{Key},StatusSet=>\%CIStatus);return$V if!$V->{Success};return$S->_Error('CRITICALITY_INVALID')if!$Criticality{$P{Criticality}};return$S->_Error('OWNER_INVALID')if defined$P{OwnerUserID}&&!$S->_UserExists($P{OwnerUserID});my$T=$S->_TypeRow(TenantID=>$P{TenantID},TypeID=>$C->{TypeID});return$S->_Error('TYPE_NOT_FOUND')if!$T;my$Attrs=$S->_AttributesValidate(Schema=>$T->{AttributeSchema},Attributes=>exists$P{Attributes}?$P{Attributes}:$C->{Attributes});return$Attrs if!$Attrs->{Success};my$J=$S->_JSON($Attrs->{Data});my@V=($P{Name},$P{Description},$P{Status},$P{Criticality},$P{OwnerUserID},$J,$P{UserID},$P{TenantID},$P{CIID},$P{ExpectedVersion});my@B=map{\$_}@V;$Kernel::OM->Get('Kernel::System::DB')->Do(SQL=>'UPDATE careoncloud_ci SET name=?,description=?,status=?,criticality=?,owner_user_id=?,attributes_json=?,version=version+1,change_time=current_timestamp,change_by=? WHERE tenant_id=? AND id=? AND version=?',Bind=>\@B)||return$S->_Error('DATABASE_ERROR');my$R=$S->_CIRow(%P);my$N=$C->{Version}+1;return$S->_Error('VERSION_CONFLICT')if!$R||$R->{Version}!=$N;$S->_Audit(%P,Action=>'cmdb.ci.updated',ObjectType=>'ci',ObjectID=>$P{CIID},Version=>$N,From=>$C->{Status},To=>$R->{Status},Details=>{key=>$C->{Key},type_id=>$C->{TypeID},criticality=>$R->{Criticality}});return{Success=>1,Data=>$R}
}

sub RelationCreate{
 my($S,%P)=@_;return$S->_TransactionRun(Code=>sub{my$A=$S->_Auth(Action=>'cmdb.manage',RequireUserID=>1,%P);return$A if!$A->{Success};return$S->_Error('CI_ID_INVALID')if!$S->_ID($P{SourceCIID})||!$S->_ID($P{TargetCIID})||$P{SourceCIID}==$P{TargetCIID};return$S->_Error('RELATION_TYPE_INVALID')if!$RelationType{$P{RelationType}//q{}};my$Source=$S->_CIRow(TenantID=>$P{TenantID},CIID=>$P{SourceCIID});my$Target=$S->_CIRow(TenantID=>$P{TenantID},CIID=>$P{TargetCIID});return$S->_Error('CI_NOT_FOUND')if!$Source||!$Target;return$S->_Error('RELATION_CYCLE')if$P{RelationType}eq'depends_on'&&$S->_DependsReachable(TenantID=>$P{TenantID},From=>$P{TargetCIID},Find=>$P{SourceCIID});my$Existing=$S->_RelationByKey(%P);return{Success=>1,Data=>$Existing,IdempotentReplay=>1}if$Existing&&$Existing->{Status}eq'active';my$DB=$Kernel::OM->Get('Kernel::System::DB');my$Version=1;if($Existing){$Version=$Existing->{Version}+1;my@V=($P{UserID},$P{TenantID},$Existing->{RelationID},$Existing->{Version});my@B=map{\$_}@V;$DB->Do(SQL=>"UPDATE careoncloud_ci_relation SET status='active',version=version+1,change_time=current_timestamp,change_by=? WHERE tenant_id=? AND id=? AND version=?",Bind=>\@B)||return$S->_Error('DATABASE_ERROR')}else{my@V=(@P{qw(TenantID SourceCIID TargetCIID RelationType)},$P{UserID},$P{UserID});my@B=map{\$_}@V;$DB->Do(SQL=>"INSERT INTO careoncloud_ci_relation (tenant_id,source_ci_id,target_ci_id,relation_type,status,version,create_time,create_by,change_time,change_by) VALUES (?,?,?,?,'active',1,current_timestamp,?,current_timestamp,?)",Bind=>\@B)||return$S->_Error('DATABASE_ERROR')}my$R=$S->_RelationByKey(%P);$S->_Audit(%P,Action=>'cmdb.relation.created',ObjectType=>'ci_relation',ObjectID=>$R->{RelationID},Version=>$Version,From=>$Existing?$Existing->{Status}:q{},To=>'active',Details=>{source_ci_id=>$P{SourceCIID},target_ci_id=>$P{TargetCIID},relation_type=>$P{RelationType}});return{Success=>1,Data=>$R}})}
sub RelationRetire{my($S,%P)=@_;return$S->_RelationRetire(Entity=>'relation',%P)}
sub RelationList{my($S,%P)=@_;my$A=$S->_Auth(Action=>'cmdb.read',%P);return$A if!$A->{Success};return$S->_Error('CI_ID_INVALID')if!$S->_ID($P{CIID});my$T=$P{TenantID};my$ID=$P{CIID};my$DB=$Kernel::OM->Get('Kernel::System::DB');$DB->Prepare(SQL=>"SELECT id,source_ci_id,target_ci_id,relation_type,status,version,create_time,change_time FROM careoncloud_ci_relation WHERE tenant_id=? AND (source_ci_id=? OR target_ci_id=?) AND status='active' ORDER BY id",Bind=>[\$T,\$ID,\$ID]);my@D;while(my@R=$DB->FetchrowArray()){push@D,$S->_RelationMap(\@R,$T)}return{Success=>1,Data=>\@D}}

sub InstanceBindingCreate{
 my($S,%P)=@_;return$S->_TransactionRun(Code=>sub{my$A=$S->_Auth(Action=>'cmdb.manage',RequireUserID=>1,%P);return$A if!$A->{Success};return$S->_Error('ID_INVALID')if!$S->_ID($P{ServiceInstanceID})||!$S->_ID($P{CIID});return$S->_Error('RELATIONSHIP_TYPE_INVALID')if!$BindingType{$P{RelationshipType}//q{}};return$S->_Error('INSTANCE_NOT_FOUND')if!$S->_InstanceRow(%P);return$S->_Error('CI_NOT_FOUND')if!$S->_CIRow(%P);my$E=$S->_BindingByKey(%P);return{Success=>1,Data=>$E,IdempotentReplay=>1}if$E&&$E->{Status}eq'active';my$DB=$Kernel::OM->Get('Kernel::System::DB');my$V=1;if($E){$V=$E->{Version}+1;my@X=($P{UserID},$P{TenantID},$E->{BindingID},$E->{Version});my@B=map{\$_}@X;$DB->Do(SQL=>"UPDATE careoncloud_service_instance_ci SET status='active',version=version+1,change_time=current_timestamp,change_by=? WHERE tenant_id=? AND id=? AND version=?",Bind=>\@B)||return$S->_Error('DATABASE_ERROR')}else{my@X=(@P{qw(TenantID ServiceInstanceID CIID RelationshipType)},$P{UserID},$P{UserID});my@B=map{\$_}@X;$DB->Do(SQL=>"INSERT INTO careoncloud_service_instance_ci (tenant_id,service_instance_id,ci_id,relationship_type,status,version,create_time,create_by,change_time,change_by) VALUES (?,?,?,?,'active',1,current_timestamp,?,current_timestamp,?)",Bind=>\@B)||return$S->_Error('DATABASE_ERROR')}my$R=$S->_BindingByKey(%P);$S->_Audit(%P,Action=>'cmdb.instance_binding.created',ObjectType=>'service_instance_ci',ObjectID=>$R->{BindingID},Version=>$V,From=>$E?$E->{Status}:q{},To=>'active',Details=>{service_instance_id=>$P{ServiceInstanceID},ci_id=>$P{CIID},relationship_type=>$P{RelationshipType}});return{Success=>1,Data=>$R}})}
sub InstanceBindingRetire{my($S,%P)=@_;return$S->_RelationRetire(Entity=>'binding',%P)}
sub InstanceBindingList{my($S,%P)=@_;my$A=$S->_Auth(Action=>'cmdb.read',%P);return$A if!$A->{Success};return$S->_Error('ID_INVALID')if!$S->_ID($P{ServiceInstanceID});my$T=$P{TenantID};my$ID=$P{ServiceInstanceID};my$DB=$Kernel::OM->Get('Kernel::System::DB');$DB->Prepare(SQL=>"SELECT id,service_instance_id,ci_id,relationship_type,status,version,create_time,change_time FROM careoncloud_service_instance_ci WHERE tenant_id=? AND service_instance_id=? AND status='active' ORDER BY id",Bind=>[\$T,\$ID]);my@D;while(my@R=$DB->FetchrowArray()){push@D,$S->_BindingMap(\@R,$T)}return{Success=>1,Data=>\@D}}

sub PortfolioList {
    my ( $S, %P ) = @_;
    my $A = $S->_Auth( Action => 'cmdb.read', %P );
    return $A if !$A->{Success};
    return $S->_Error('SERVICE_ID_INVALID') if defined $P{ServiceID} && !$S->_ID( $P{ServiceID} );
    my $T = $P{TenantID};
    my @V = ($T);
    my $Where = 's.tenant_id=?';
    if ( defined $P{ServiceID} ) { $Where .= ' AND s.id=?'; push @V, $P{ServiceID}; }
    my @B = map { \$_ } @V;
    my $DB = $Kernel::OM->Get('Kernel::System::DB');
    $DB->Prepare(
        SQL => "SELECT s.id,s.key_name,s.name,s.description,s.status,c.id,c.name,i.id,i.key_name,i.name,i.service_model,i.status,i.criticality,i.support_group_id,g.name FROM careoncloud_service s LEFT JOIN careoncloud_service_category_service cs ON cs.tenant_id=s.tenant_id AND cs.service_id=s.id LEFT JOIN careoncloud_service_category c ON c.tenant_id=cs.tenant_id AND c.id=cs.category_id LEFT JOIN careoncloud_service_instance i ON i.tenant_id=s.tenant_id AND i.service_id=s.id LEFT JOIN groups_table g ON g.id=i.support_group_id WHERE $Where ORDER BY c.name,s.name,i.name,s.id,i.id",
        Bind => \@B,
        Limit => $Kernel::OM->Get('Kernel::Config')->Get('CareOnCloud::CMDB::ListLimit') // 200,
    );
    my @D;
    while ( my @R = $DB->FetchrowArray() ) {
        push @D, {
            TenantID => $T, ServiceID => 0 + $R[0], ServiceKey => $R[1], ServiceName => $R[2],
            ServiceDescription => $R[3], ServiceStatus => $R[4],
            CategoryID => defined $R[5] ? 0 + $R[5] : undef, CategoryName => $R[6],
            ServiceInstanceID => defined $R[7] ? 0 + $R[7] : undef, InstanceKey => $R[8], InstanceName => $R[9],
            ServiceModel => $R[10], InstanceStatus => $R[11], Criticality => $R[12],
            SupportGroupID => defined $R[13] ? 0 + $R[13] : undef, SupportGroupName => $R[14],
        };
    }
    return { Success => 1, Data => \@D };
}

sub ServiceGraphGet{
 my($S,%P)=@_;my$A=$S->_Auth(Action=>'cmdb.read',%P);return$A if!$A->{Success};return$S->_Error('ID_INVALID')if!$S->_ID($P{ServiceID});return$S->_Error('SERVICE_NOT_FOUND')if!$S->_ServiceExists(%P);my$I=$S->InstanceList(%P);return$I if!$I->{Success};my@Bindings;for my$Instance(@{$I->{Data}}){my$B=$S->InstanceBindingList(Subject=>$P{Subject},TenantID=>$P{TenantID},ServiceInstanceID=>$Instance->{ServiceInstanceID});return$B if!$B->{Success};push@Bindings,@{$B->{Data}}}my%Seen=map{$_->{CIID}=>1}@Bindings;my@Queue=keys%Seen;my@Edges;my$DB=$Kernel::OM->Get('Kernel::System::DB');while(@Queue){return$S->_Error('GRAPH_LIMIT_EXCEEDED')if keys(%Seen)>500;my$ID=shift@Queue;my$T=$P{TenantID};$DB->Prepare(SQL=>"SELECT id,source_ci_id,target_ci_id,relation_type,status,version,create_time,change_time FROM careoncloud_ci_relation WHERE tenant_id=? AND source_ci_id=? AND status='active' ORDER BY id",Bind=>[\$T,\$ID]);while(my@R=$DB->FetchrowArray()){my$E=$S->_RelationMap(\@R,$T);push@Edges,$E;if(!$Seen{$E->{TargetCIID}}){$Seen{$E->{TargetCIID}}=1;push@Queue,$E->{TargetCIID}}}}my@Nodes=map{$S->_CIRow(TenantID=>$P{TenantID},CIID=>$_)}sort{$a<=>$b}keys%Seen;return{Success=>1,Data=>{TenantID=>$P{TenantID},ServiceID=>0+$P{ServiceID},Instances=>$I->{Data},Bindings=>\@Bindings,Nodes=>\@Nodes,Edges=>\@Edges}} }

sub _RelationRetire{my($S,%P)=@_;return$S->_TransactionRun(Code=>sub{my$A=$S->_Auth(Action=>'cmdb.manage',RequireUserID=>1,%P);return$A if!$A->{Success};return$S->_Error('VERSION_REQUIRED')if!$S->_ID($P{ExpectedVersion});my($Table,$IDKey,$Get,$Action,$Object)= $P{Entity}eq'relation'?('careoncloud_ci_relation','RelationID','_RelationByID','cmdb.relation.retired','ci_relation'):('careoncloud_service_instance_ci','BindingID','_BindingByID','cmdb.instance_binding.retired','service_instance_ci');return$S->_Error('ID_INVALID')if!$S->_ID($P{$IDKey});my$C=$S->$Get(TenantID=>$P{TenantID},$IDKey=>$P{$IDKey});return$S->_Error('NOT_FOUND')if!$C;return$S->_Error('VERSION_CONFLICT')if$C->{Version}!=$P{ExpectedVersion};return{Success=>1,Data=>$C,IdempotentReplay=>1}if$C->{Status}eq'retired';my@V=($P{UserID},$P{TenantID},$P{$IDKey},$P{ExpectedVersion});my@B=map{\$_}@V;$Kernel::OM->Get('Kernel::System::DB')->Do(SQL=>"UPDATE $Table SET status='retired',version=version+1,change_time=current_timestamp,change_by=? WHERE tenant_id=? AND id=? AND version=?",Bind=>\@B)||return$S->_Error('DATABASE_ERROR');my$R=$S->$Get(TenantID=>$P{TenantID},$IDKey=>$P{$IDKey});my$N=$C->{Version}+1;return$S->_Error('VERSION_CONFLICT')if!$R||$R->{Version}!=$N;$S->_Audit(%P,Action=>$Action,ObjectType=>$Object,ObjectID=>$P{$IDKey},Version=>$N,From=>'active',To=>'retired',Details=>{entity=>$P{Entity}});return{Success=>1,Data=>$R}})}

sub _List{my($S,%P)=@_;my$A=$S->_Auth(Action=>'cmdb.read',%P);return$A if!$A->{Success};my$Limit=$P{Limit}//100;my$Max=$Kernel::OM->Get('Kernel::Config')->Get('CareOnCloud::CMDB::ListLimit')//200;return$S->_Error('LIMIT_INVALID')if!$S->_ID($Limit)||$Limit>$Max;my$After=$P{AfterID}//0;return$S->_Error('CURSOR_INVALID')if$After!~m{\A[0-9]+\z}smx;my($Table,$Cols)=$P{Entity}eq'type'?('careoncloud_ci_type','id,tenant_id,key_name,name,description,status,attribute_schema_json,version,create_time,change_time'):('careoncloud_ci','id,tenant_id,type_id,key_name,name,description,status,criticality,owner_user_id,attributes_json,version,create_time,change_time');my@V=($P{TenantID},$After);my$Where='tenant_id=? AND id>?';if(defined$P{Status}){$Where.=' AND status=?';push@V,$P{Status}}if($P{Entity}eq'ci'&&defined$P{TypeID}){return$S->_Error('TYPE_ID_INVALID')if!$S->_ID($P{TypeID});$Where.=' AND type_id=?';push@V,$P{TypeID}}my@B=map{\$_}@V;my$DB=$Kernel::OM->Get('Kernel::System::DB');$DB->Prepare(SQL=>"SELECT $Cols FROM $Table WHERE $Where ORDER BY id",Bind=>\@B,Limit=>$Limit);my@D;while(my@R=$DB->FetchrowArray()){push@D,$P{Entity}eq'type'?$S->_TypeMap(\@R):$S->_CIMap(\@R)}return{Success=>1,Data=>\@D,NextID=>@D?($P{Entity}eq'type'?$D[-1]->{TypeID}:$D[-1]->{CIID}):0+$After}}

sub _BaseValidate{my($S,%P)=@_;return$S->_Error('KEY_INVALID')if($P{Key}//q{})!~m{\A[a-z0-9][a-z0-9._-]{1,99}\z}smx;return$S->_Error('NAME_INVALID')if!length($P{Name}//q{})||length$P{Name}>200||$P{Name}=~m{[\x00-\x1f]}smx;return$S->_Error('DESCRIPTION_INVALID')if length($P{Description}//q{})>4000||($P{Description}//q{})=~m{[\x00-\x08\x0b\x0c\x0e-\x1f]}smx;return$S->_Error('STATUS_INVALID')if!$P{StatusSet}->{$P{Status}//q{}};return{Success=>1}}
sub _SchemaValidate{my($S,$X)=@_;$X//={version=>1,fields=>[]};return$S->_Error('SCHEMA_INVALID')if ref$X ne'HASH'||($X->{version}//0)!=1||ref$X->{fields}ne'ARRAY'||@{$X->{fields}}>50;my%K;my@F;for my$F(@{$X->{fields}}){return$S->_Error('SCHEMA_INVALID')if ref$F ne'HASH'||($F->{key}//q{})!~m{\A[a-z][a-z0-9_]{0,49}\z}smx||$K{$F->{key}}++||!$FieldType{$F->{type}//q{}};my%N=(key=>$F->{key},type=>$F->{type},required=>$F->{required}?1:0);if($F->{type}eq'select'){return$S->_Error('SCHEMA_INVALID')if ref$F->{options}ne'ARRAY'||!@{$F->{options}}||@{$F->{options}}>100;my%O;return$S->_Error('SCHEMA_INVALID')if grep{ref$_||!length||length>100||$O{$_}++}@{$F->{options}};$N{options}=[@{$F->{options}}]}push@F,\%N}return{Success=>1,Data=>{version=>1,fields=>\@F}}}
sub _AttributesValidate{my($S,%P)=@_;my$A=$P{Attributes}//{};return$S->_Error('ATTRIBUTES_INVALID')if ref$A ne'HASH'||keys(%$A)>50;my%F=map{$_->{key}=>$_}@{$P{Schema}->{fields}//[]};for my$K(keys%$A){return$S->_Error('ATTRIBUTE_UNKNOWN')if!$F{$K};my$V=$A->{$K};return$S->_Error('ATTRIBUTE_VALUE_INVALID')if ref$V||length($V//q{})>1000;my$T=$F{$K}->{type};return$S->_Error('ATTRIBUTE_VALUE_INVALID')if$T eq'number'&&($V//q{})!~m{\A-?(?:0|[1-9][0-9]*)(?:\.[0-9]+)?\z}smx;return$S->_Error('ATTRIBUTE_VALUE_INVALID')if$T eq'boolean'&&($V//q{})!~m{\A(?:0|1)\z}smx;if($T eq'select'){my%O=map{$_=>1}@{$F{$K}->{options}};return$S->_Error('ATTRIBUTE_VALUE_INVALID')if!$O{$V//q{}}}}for my$K(keys%F){return$S->_Error('ATTRIBUTE_REQUIRED')if$F{$K}->{required}&&!exists$A->{$K}}return{Success=>1,Data=>{%$A}}}
sub _Auth{my($S,%P)=@_;return$S->_Error('CMDB_DISABLED')if!$Kernel::OM->Get('Kernel::Config')->Get('CareOnCloud::CMDB::Enabled');return$S->_Error('TENANT_ID_INVALID')if($P{TenantID}//q{})!~m{\A[a-z0-9][a-z0-9_-]{1,127}\z}smx;return$S->_Error('USER_ID_INVALID')if$P{RequireUserID}&&!$S->_ID($P{UserID});my$D=$Kernel::OM->Get('Kernel::System::CareOnCloud::TenantGuard')->DecisionGet(Subject=>$P{Subject},Resource=>{TenantID=>$P{TenantID}},Action=>$P{Action});return$D->{Allowed}?{Success=>1}:$S->_Error('FORBIDDEN',$D->{Reason})}
sub _Audit{my($S,%P)=@_;my$R=$Kernel::OM->Get('Kernel::System::CareOnCloud::Audit')->Record(TenantID=>$P{TenantID},ActorType=>'agent',ActorID=>'agent:'.$P{UserID},Action=>$P{Action},ObjectType=>$P{ObjectType},ObjectID=>''.$P{ObjectID},CorrelationID=>'cmdb:'.$P{ObjectType}.':'.$P{ObjectID},DedupeKey=>'cmdb:'.$P{ObjectType}.':'.$P{ObjectID}.':version:'.$P{Version},FromState=>$P{From},ToState=>$P{To},Outcome=>'success',Details=>$P{Details});die"AUDIT_WRITE_FAILED\n"if!$R->{Success};return 1}
sub _TransactionRun{my($S,%P)=@_;my$DB=$Kernel::OM->Get('Kernel::System::DB');my$H=$DB->Connect();return$S->_Error('DATABASE_UNAVAILABLE')if!$H;my$Own=$H->{AutoCommit}?1:0;my$R;my$OK=eval{$DB->BeginWork()if$Own;$R=$P{Code}->();die(($R->{Error}//'TRANSACTION_FAILED')."\n")if!$R->{Success};$H->commit()if$Own;1};if(!$OK){my$E=$@||'TRANSACTION_FAILED';eval{$DB->Rollback()}if$Own;my($C)=$E=~m{\A([A-Z0-9_]+)};return$S->_Error($C||'TRANSACTION_FAILED')}return$R}

sub _CategoryRow{my($S,%P)=@_;return$S->_CategorySelect('tenant_id=? AND id=?',$P{TenantID},$P{CategoryID})}sub _CategoryByKey{my($S,%P)=@_;return$S->_CategorySelect('tenant_id=? AND key_name=?',$P{TenantID},$P{Key})}sub _CategorySelect{my($S,$W,@V)=@_;my@B=map{\$_}@V;my$DB=$Kernel::OM->Get('Kernel::System::DB');$DB->Prepare(SQL=>"SELECT id,tenant_id,key_name,name,description,status,version,create_time,change_time FROM careoncloud_service_category WHERE $W",Bind=>\@B,Limit=>1);my@R=$DB->FetchrowArray();return@R?$S->_CategoryMap(\@R):undef}sub _CategoryMap{my($S,$R)=@_;return{CategoryID=>0+$R->[0],TenantID=>$R->[1],Key=>$R->[2],Name=>$R->[3],Description=>$R->[4],Status=>$R->[5],Version=>0+$R->[6],CreateTime=>$R->[7],ChangeTime=>$R->[8]}}
sub _InstanceRow{my($S,%P)=@_;return$S->_InstanceSelect('tenant_id=? AND id=?',$P{TenantID},$P{ServiceInstanceID})}sub _InstanceByKey{my($S,%P)=@_;return$S->_InstanceSelect('tenant_id=? AND key_name=?',$P{TenantID},$P{Key})}sub _InstanceSelect{my($S,$W,@V)=@_;my@B=map{\$_}@V;my$DB=$Kernel::OM->Get('Kernel::System::DB');$DB->Prepare(SQL=>"SELECT id,tenant_id,service_id,key_name,name,description,support_group_id,service_model,status,criticality,version,create_time,change_time FROM careoncloud_service_instance WHERE $W",Bind=>\@B,Limit=>1);my@R=$DB->FetchrowArray();return@R?$S->_InstanceMap(\@R):undef}sub _InstanceMap{my($S,$R)=@_;return{ServiceInstanceID=>0+$R->[0],TenantID=>$R->[1],ServiceID=>0+$R->[2],Key=>$R->[3],Name=>$R->[4],Description=>$R->[5],SupportGroupID=>defined$R->[6]?0+$R->[6]:undef,ServiceModel=>$R->[7],Status=>$R->[8],Criticality=>$R->[9],Version=>0+$R->[10],CreateTime=>$R->[11],ChangeTime=>$R->[12]}}
sub _TypeRow{my($S,%P)=@_;return$S->_TypeSelect('tenant_id=? AND id=?',$P{TenantID},$P{TypeID})}sub _TypeByKey{my($S,%P)=@_;return$S->_TypeSelect('tenant_id=? AND key_name=?',$P{TenantID},$P{Key})}sub _TypeSelect{my($S,$W,@V)=@_;my@B=map{\$_}@V;my$DB=$Kernel::OM->Get('Kernel::System::DB');$DB->Prepare(SQL=>"SELECT id,tenant_id,key_name,name,description,status,attribute_schema_json,version,create_time,change_time FROM careoncloud_ci_type WHERE $W",Bind=>\@B,Limit=>1);my@R=$DB->FetchrowArray();return@R?$S->_TypeMap(\@R):undef}sub _TypeMap{my($S,$R)=@_;my$J=$S->_Decode($R->[6]);return{TypeID=>0+$R->[0],TenantID=>$R->[1],Key=>$R->[2],Name=>$R->[3],Description=>$R->[4],Status=>$R->[5],AttributeSchema=>$J,Version=>0+$R->[7],CreateTime=>$R->[8],ChangeTime=>$R->[9]}}
sub _CIRow{my($S,%P)=@_;return$S->_CISelect('tenant_id=? AND id=?',$P{TenantID},$P{CIID})}sub _CIByKey{my($S,%P)=@_;return$S->_CISelect('tenant_id=? AND key_name=?',$P{TenantID},$P{Key})}sub _CISelect{my($S,$W,@V)=@_;my@B=map{\$_}@V;my$DB=$Kernel::OM->Get('Kernel::System::DB');$DB->Prepare(SQL=>"SELECT id,tenant_id,type_id,key_name,name,description,status,criticality,owner_user_id,attributes_json,version,create_time,change_time FROM careoncloud_ci WHERE $W",Bind=>\@B,Limit=>1);my@R=$DB->FetchrowArray();return@R?$S->_CIMap(\@R):undef}sub _CIMap{my($S,$R)=@_;return{CIID=>0+$R->[0],TenantID=>$R->[1],TypeID=>0+$R->[2],Key=>$R->[3],Name=>$R->[4],Description=>$R->[5],Status=>$R->[6],Criticality=>$R->[7],OwnerUserID=>$R->[8],Attributes=>$S->_Decode($R->[9]),Version=>0+$R->[10],CreateTime=>$R->[11],ChangeTime=>$R->[12]}}
sub _RelationByKey{my($S,%P)=@_;my@V=@P{qw(TenantID SourceCIID TargetCIID RelationType)};return$S->_RelationSelect('tenant_id=? AND source_ci_id=? AND target_ci_id=? AND relation_type=?',@V)}sub _RelationByID{my($S,%P)=@_;return$S->_RelationSelect('tenant_id=? AND id=?',$P{TenantID},$P{RelationID})}sub _RelationSelect{my($S,$W,@V)=@_;my@B=map{\$_}@V;my$DB=$Kernel::OM->Get('Kernel::System::DB');$DB->Prepare(SQL=>"SELECT id,source_ci_id,target_ci_id,relation_type,status,version,create_time,change_time,tenant_id FROM careoncloud_ci_relation WHERE $W",Bind=>\@B,Limit=>1);my@R=$DB->FetchrowArray();return@R?$S->_RelationMap(\@R,$R[8]):undef}sub _RelationMap{my($S,$R,$T)=@_;return{RelationID=>0+$R->[0],TenantID=>$T,SourceCIID=>0+$R->[1],TargetCIID=>0+$R->[2],RelationType=>$R->[3],Status=>$R->[4],Version=>0+$R->[5],CreateTime=>$R->[6],ChangeTime=>$R->[7]}}
sub _BindingByKey{my($S,%P)=@_;return$S->_BindingSelect('tenant_id=? AND service_instance_id=? AND ci_id=? AND relationship_type=?',@P{qw(TenantID ServiceInstanceID CIID RelationshipType)})}sub _BindingByID{my($S,%P)=@_;return$S->_BindingSelect('tenant_id=? AND id=?',$P{TenantID},$P{BindingID})}sub _BindingSelect{my($S,$W,@V)=@_;my@B=map{\$_}@V;my$DB=$Kernel::OM->Get('Kernel::System::DB');$DB->Prepare(SQL=>"SELECT id,service_instance_id,ci_id,relationship_type,status,version,create_time,change_time,tenant_id FROM careoncloud_service_instance_ci WHERE $W",Bind=>\@B,Limit=>1);my@R=$DB->FetchrowArray();return@R?$S->_BindingMap(\@R,$R[8]):undef}sub _BindingMap{my($S,$R,$T)=@_;return{BindingID=>0+$R->[0],TenantID=>$T,ServiceInstanceID=>0+$R->[1],CIID=>0+$R->[2],RelationshipType=>$R->[3],Status=>$R->[4],Version=>0+$R->[5],CreateTime=>$R->[6],ChangeTime=>$R->[7]}}
sub _DependsReachable{my($S,%P)=@_;my%Seen;my@Q=($P{From});my$DB=$Kernel::OM->Get('Kernel::System::DB');while(@Q){my$N=shift@Q;return 1 if$N==$P{Find};next if$Seen{$N}++;my$T=$P{TenantID};$DB->Prepare(SQL=>"SELECT target_ci_id FROM careoncloud_ci_relation WHERE tenant_id=? AND source_ci_id=? AND relation_type='depends_on' AND status='active'",Bind=>[\$T,\$N]);while(my($X)=$DB->FetchrowArray()){push@Q,$X}return 1 if keys(%Seen)>500}return 0}
sub _ServiceExists{my($S,%P)=@_;my$T=$P{TenantID};my$ID=$P{ServiceID};my$DB=$Kernel::OM->Get('Kernel::System::DB');$DB->Prepare(SQL=>'SELECT 1 FROM careoncloud_service WHERE tenant_id=? AND id=?',Bind=>[\$T,\$ID],Limit=>1);my($X)=$DB->FetchrowArray();return$X}sub _GroupExists{my($S,$ID)=@_;return 0 if!$S->_ID($ID);my$DB=$Kernel::OM->Get('Kernel::System::DB');$DB->Prepare(SQL=>'SELECT 1 FROM groups_table WHERE id=?',Bind=>[\$ID],Limit=>1);my($X)=$DB->FetchrowArray();return$X}sub _UserExists{my($S,$ID)=@_;return 0 if!$S->_ID($ID);my$DB=$Kernel::OM->Get('Kernel::System::DB');$DB->Prepare(SQL=>'SELECT 1 FROM users WHERE id=?',Bind=>[\$ID],Limit=>1);my($X)=$DB->FetchrowArray();return$X}sub _ID{return defined$_[1]&&$_[1]=~m{\A[1-9][0-9]*\z}smx?1:0}sub _JSON{return$Kernel::OM->Get('Kernel::System::JSON')->Encode(Data=>$_[1],SortKeys=>1)}sub _Decode{my($S,$J)=@_;my$D=eval{$Kernel::OM->Get('Kernel::System::JSON')->Decode(Data=>$J)};return ref$D eq'HASH'?$D:{}}sub _Error{my($S,$E,$R)=@_;return{Success=>0,Error=>$E,Reason=>$R//$E}}
1;
