# --
# CareOnCloud ESM enterprise service management platform.
# SPDX-License-Identifier: GPL-3.0-only
# --
package Kernel::System::D724::Problem;
use v5.24;use strict;use warnings;
our$VERSION='0.2.2';our@ObjectDependencies=('Kernel::Config','Kernel::System::D724::Audit','Kernel::System::D724::TenantDirectory','Kernel::System::D724::TenantGuard','Kernel::System::DB');
my%W=(low=>1,medium=>2,high=>3,critical=>4);my%Category=map{$_=>1}qw(application infrastructure network security supplier process capacity availability);
sub new{return bless{},$_[0]}
sub PriorityAssess{my($S,%P)=@_;return$S->_E('IMPACT_INVALID')if!$W{$P{Impact}//q{}};return$S->_E('URGENCY_INVALID')if!$W{$P{Urgency}//q{}};my$Score=$W{$P{Impact}}*$W{$P{Urgency}};my$Priority=$Score>=12?1:$Score>=8?2:$Score>=4?3:4;return{Success=>1,Data=>{Score=>$Score,Priority=>$Priority}}}
sub Create{my($S,%P)=@_;return$S->_Tx(sub{my$A=$S->_Auth(Action=>'case.update',%P);return$A if!$A->{Success};return$S->_E('TITLE_INVALID')if!length($P{Title}//q{})||length($P{Title})>250;return$S->_E('CATEGORY_INVALID')if!$Category{$P{Category}//q{}};for(qw(Symptom BusinessImpact)){return$S->_E(uc($_).'_INVALID')if!length($P{$_}//q{})||length($P{$_})>4000}my$R=$S->PriorityAssess(%P);return$R if!$R->{Success};my$Tmp='TMP-'.time().'-'.int(rand(1000000));my@V=($P{TenantID},$Tmp,$P{Title},$P{Symptom},$P{BusinessImpact},$P{Category},$P{Impact},$P{Urgency},$R->{Data}->{Priority},q{},q{},q{},0,'draft',$P{UserID},$P{UserID});my@B=map{\$_}@V;my$DB=$Kernel::OM->Get('Kernel::System::DB');$DB->Do(SQL=>'INSERT INTO d724_problem (tenant_id,problem_number,title,symptom,business_impact,category,impact,urgency,priority,root_cause,workaround,permanent_fix,known_error,status,version,create_time,create_by,change_time,change_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,1,current_timestamp,?,current_timestamp,?)',Bind=>\@B)||return$S->_E('DATABASE_ERROR');$DB->Prepare(SQL=>'SELECT id FROM d724_problem WHERE tenant_id=? AND problem_number=?',Bind=>[\$P{TenantID},\$Tmp],Limit=>1);my($ID)=$DB->FetchrowArray();my$N=sprintf'PRB-%010d',$ID;$DB->Do(SQL=>'UPDATE d724_problem SET problem_number=? WHERE tenant_id=? AND id=?',Bind=>[\$N,\$P{TenantID},\$ID])||return$S->_E('DATABASE_ERROR');my$D=$S->_Get(TenantID=>$P{TenantID},ProblemID=>$ID);$S->_Audit(%P,Action=>'problem.created',Data=>$D,From=>q{},To=>'draft');return{Success=>1,Data=>$D}})}
sub Start{my($S,%P)=@_;return$S->_Status(Action=>'case.update',From=>['draft'],To=>'investigating',%P)}
sub Diagnose{my($S,%P)=@_;return$S->_Tx(sub{my$A=$S->_Auth(Action=>'case.update',%P);return$A if!$A->{Success};my$C=$S->_Locked(%P);return$C if!$C->{Success};return$S->_E('TRANSITION_INVALID')if$C->{Data}->{Status}!~m{\A(?:investigating|known_error)\z};for(qw(RootCause Workaround)){return$S->_E(uc($_).'_INVALID')if length($P{$_}//q{})>4000}my@V=($P{RootCause}//q{},$P{Workaround}//q{},$P{UserID},$P{TenantID},$P{ProblemID},$P{ExpectedVersion});my@B=map{\$_}@V;$Kernel::OM->Get('Kernel::System::DB')->Do(SQL=>'UPDATE d724_problem SET root_cause=?,workaround=?,version=version+1,change_time=current_timestamp,change_by=? WHERE tenant_id=? AND id=? AND version=?',Bind=>\@B)||return$S->_E('DATABASE_ERROR');my$D=$S->_Get(%P);$S->_Audit(%P,Action=>'problem.diagnosed',Data=>$D,From=>$C->{Data}->{Status},To=>$D->{Status});return{Success=>1,Data=>$D}})}
sub PublishKnownError{my($S,%P)=@_;return$S->_Tx(sub{my$A=$S->_Auth(Action=>'case.update',%P);return$A if!$A->{Success};my$C=$S->_Locked(%P);return$C if!$C->{Success};return$S->_E('TRANSITION_INVALID')if$C->{Data}->{Status}ne'investigating';return$S->_E('DIAGNOSIS_REQUIRED')if!length($C->{Data}->{RootCause})||!length($C->{Data}->{Workaround});my$R=$S->_UpdateStatus(Current=>$C->{Data},To=>'known_error',KnownError=>1,%P);return$R})}
sub Resolve{my($S,%P)=@_;return$S->_Tx(sub{my$A=$S->_Auth(Action=>'case.update',%P);return$A if!$A->{Success};my$C=$S->_Locked(%P);return$C if!$C->{Success};return$S->_E('TRANSITION_INVALID')if$C->{Data}->{Status}!~m{\A(?:investigating|known_error)\z};return$S->_E('ROOT_CAUSE_REQUIRED')if!length($C->{Data}->{RootCause});return$S->_E('PERMANENT_FIX_INVALID')if!length($P{PermanentFix}//q{})||length($P{PermanentFix})>4000;my$Fix=$P{PermanentFix};my$DB=$Kernel::OM->Get('Kernel::System::DB');$DB->Do(SQL=>'UPDATE d724_problem SET permanent_fix=?,status=?,version=version+1,change_time=current_timestamp,change_by=? WHERE tenant_id=? AND id=? AND version=?',Bind=>[\$Fix,\'resolved',\$P{UserID},\$P{TenantID},\$P{ProblemID},\$P{ExpectedVersion}])||return$S->_E('DATABASE_ERROR');my$D=$S->_Get(%P);$S->_Audit(%P,Action=>'problem.status_changed',Data=>$D,From=>$C->{Data}->{Status},To=>'resolved');return{Success=>1,Data=>$D}})}
sub Close{my($S,%P)=@_;return$S->_Status(Action=>'case.delete',From=>['resolved'],To=>'closed',%P)}
sub Reopen{my($S,%P)=@_;return$S->_Status(Action=>'case.delete',From=>[qw(resolved closed)],To=>'investigating',%P)}
sub Get{my($S,%P)=@_;my$A=$S->_Auth(Action=>'case.read',%P);return$A if!$A->{Success};my$D=$S->_Get(%P);return$D?{Success=>1,Data=>$D}:$S->_E('NOT_FOUND')}
sub List{my($S,%P)=@_;my$A=$S->_Auth(Action=>'case.read',%P);return$A if!$A->{Success};my$T=$P{TenantID};my$DB=$Kernel::OM->Get('Kernel::System::DB');$DB->Prepare(SQL=>'SELECT id FROM d724_problem WHERE tenant_id=? ORDER BY priority,id DESC',Bind=>[\$T],Limit=>$Kernel::OM->Get('Kernel::Config')->Get('D724::Problem::ListLimit')//200);my@I;while(my($I)=$DB->FetchrowArray()){push@I,$I}return{Success=>1,Data=>[map{$S->_Get(TenantID=>$T,ProblemID=>$_)}@I]}}
sub _Status{my($S,%P)=@_;return$S->_Tx(sub{my$A=$S->_Auth(Action=>$P{Action},%P);return$A if!$A->{Success};my$C=$S->_Locked(%P);return$C if!$C->{Success};my%F=map{$_=>1}@{$P{From}};return$S->_E('TRANSITION_INVALID')if!$F{$C->{Data}->{Status}};return$S->_UpdateStatus(Current=>$C->{Data},%P)})}
sub _UpdateStatus{my($S,%P)=@_;my$K=$P{KnownError}//$P{Current}->{KnownError};my@V=($P{To},$K,$P{UserID},$P{TenantID},$P{ProblemID},$P{ExpectedVersion});my@B=map{\$_}@V;$Kernel::OM->Get('Kernel::System::DB')->Do(SQL=>'UPDATE d724_problem SET status=?,known_error=?,version=version+1,change_time=current_timestamp,change_by=? WHERE tenant_id=? AND id=? AND version=?',Bind=>\@B)||return$S->_E('DATABASE_ERROR');my$D=$S->_Get(%P);$S->_Audit(%P,Action=>'problem.status_changed',Data=>$D,From=>$P{Current}->{Status},To=>$P{To});return{Success=>1,Data=>$D}}
sub _Locked{my($S,%P)=@_;return$S->_E('VERSION_REQUIRED')if($P{ExpectedVersion}//q{})!~m{\A[1-9][0-9]*\z};my$DB=$Kernel::OM->Get('Kernel::System::DB');$DB->Prepare(SQL=>'SELECT id FROM d724_problem WHERE tenant_id=? AND id=? FOR UPDATE',Bind=>[\$P{TenantID},\$P{ProblemID}]);my($ID)=$DB->FetchrowArray();return$S->_E('NOT_FOUND')if!$ID;my$D=$S->_Get(%P);return$S->_E('NOT_FOUND')if!$D;return$S->_E('VERSION_CONFLICT')if$D->{Version}!=$P{ExpectedVersion};return{Success=>1,Data=>$D}}
sub _Get{my($S,%P)=@_;return if($P{ProblemID}//q{})!~m{\A[1-9][0-9]*\z};my$T=$P{TenantID};my$I=$P{ProblemID};my$DB=$Kernel::OM->Get('Kernel::System::DB');$DB->Prepare(SQL=>'SELECT id,problem_number,title,symptom,business_impact,category,impact,urgency,priority,root_cause,workaround,permanent_fix,known_error,status,version,create_time,change_time FROM d724_problem WHERE tenant_id=? AND id=?',Bind=>[\$T,\$I],Limit=>1);my@R=$DB->FetchrowArray();return if!@R;return{ProblemID=>0+$R[0],TenantID=>$T,ProblemNumber=>$R[1],Title=>$R[2],Symptom=>$R[3],BusinessImpact=>$R[4],Category=>$R[5],Impact=>$R[6],Urgency=>$R[7],Priority=>0+$R[8],RootCause=>$R[9],Workaround=>$R[10],PermanentFix=>$R[11],KnownError=>$R[12]?1:0,Status=>$R[13],Version=>0+$R[14],CreateTime=>$R[15],ChangeTime=>$R[16]}}
sub _Auth{my($S,%P)=@_;return$S->_E('PROBLEM_DISABLED')if!$Kernel::OM->Get('Kernel::Config')->Get('D724::Problem::Enabled');return$S->_E('TENANT_ID_INVALID')if($P{TenantID}//q{})!~m{\A[a-z0-9][a-z0-9._:-]{1,127}\z};return$S->_E('USER_ID_INVALID')if($P{UserID}//q{})!~m{\A[1-9][0-9]*\z};my$Sub=$P{Subject};if(ref$Sub ne'HASH'){my$C=$Kernel::OM->Get('Kernel::System::D724::TenantDirectory')->ContextGet(UserID=>$P{UserID});return$C if!$C->{Success};$Sub=$C->{Subject}}my$D=$Kernel::OM->Get('Kernel::System::D724::TenantGuard')->DecisionGet(Subject=>$Sub,Resource=>{TenantID=>$P{TenantID}},Action=>$P{Action});return$D->{Allowed}?{Success=>1,Subject=>$Sub}:$S->_E('FORBIDDEN',$D->{Reason})}
sub _Audit{my($S,%P)=@_;my$D=$P{Data};my$R=$Kernel::OM->Get('Kernel::System::D724::Audit')->Record(TenantID=>$P{TenantID},ActorType=>'agent',ActorID=>'agent:'.$P{UserID},Action=>$P{Action},ObjectType=>'problem',ObjectID=>''.$D->{ProblemID},CorrelationID=>'problem:'.$D->{ProblemID},DedupeKey=>'problem:'.$D->{ProblemID}.':v:'.$D->{Version},FromState=>$P{From},ToState=>$P{To},Outcome=>'success',Details=>{problem_number=>$D->{ProblemNumber},priority=>$D->{Priority},known_error=>$D->{KnownError}});die"AUDIT_WRITE_FAILED\n"if!$R->{Success}}
sub _Tx{my($S,$Code)=@_;my$DB=$Kernel::OM->Get('Kernel::System::DB');my$H=$DB->Connect();my$Own=$H->{AutoCommit}?1:0;my$Savepoint='d724_problem_'.int(rand 1_000_000_000);my$R;my$OK=eval{$Own?$DB->BeginWork():$DB->Do(SQL=>"SAVEPOINT $Savepoint");$R=$Code->();die(($R->{Error}//'FAILED')."\n")if!$R->{Success};$Own?$H->commit():$DB->Do(SQL=>"RELEASE SAVEPOINT $Savepoint");1};if(!$OK){my$Error=$@||'FAILED';eval{$Own?$DB->Rollback():$DB->Do(SQL=>"ROLLBACK TO SAVEPOINT $Savepoint")};my($E)=$Error=~m{\A([A-Z0-9_]+)};return$S->_E($E||'FAILED')}return$R}
sub _E{my($S,$E,$R)=@_;return{Success=>0,Error=>$E,Reason=>$R//$E}}
1;
