# --
# SPDX-License-Identifier: GPL-3.0-only
# --
use v5.24;use strict;use warnings;use utf8;use Test2::V0;use Kernel::System::UnitTest::RegisterOM;use Archive::Zip qw(AZ_OK);use File::Temp qw(tempfile);use Encode qw(encode);
$Kernel::OM->ObjectParamAdd('Kernel::System::UnitTest::Helper'=>{RestoreDatabase=>1});my$Helper=$Kernel::OM->Get('Kernel::System::UnitTest::Helper');$Helper->ConfigSettingChange(Key=>'D724::CMDB::Enabled',Value=>1);$Helper->ConfigSettingChange(Key=>'D724::Catalog::Enabled',Value=>1);$Helper->ConfigSettingChange(Key=>'D724::Audit::Enabled',Value=>1);$Helper->ConfigSettingChange(Key=>'D724::TenantGuard::Enabled',Value=>1);$Helper->ConfigSettingChange(Key=>'D724::TenantGuard::AllowPlatformAdmin',Value=>1);my$Workbook=$Kernel::OM->Get('Kernel::System::D724::CMDBWorkbook');
sub X{my$V=shift;$V=~s{&}{&amp;}g;$V=~s{<}{&lt;}g;$V=~s{>}{&gt;}g;return$V}
sub Sheet{my($Rows)=@_;my$XML=q{<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>};my$N=0;for my$R(@$Rows){$N++;$XML.="<row r=\"$N\">";for my$I(0..$#$R){my$C=chr(65+$I);$XML.='<c r="'.$C.$N.'" t="inlineStr"><is><t>'.X($R->[$I]).'</t></is></c>'}$XML.='</row>'}return$XML.'</sheetData></worksheet>'}
sub Add{my($Z,$Data,$Name)=@_;return$Z->addString(encode('UTF-8',$Data),$Name)}
sub Book{my($Bad,$Suffix)=@_;$Suffix=length($Suffix//q{})?" $Suffix":q{};my($CustomerA,$CustomerB)=("Panço$Suffix","İş Bankası Almanya$Suffix");my($FH,$Path)=tempfile(SUFFIX=>'.xlsx');close$FH;my$Z=Archive::Zip->new();Add($Z,q{<?xml version="1.0"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Müşteri-Servis Eşleme" sheetId="1" r:id="rId1"/><sheet name="Müşteriler" sheetId="2" r:id="rId2"/><sheet name="Gözden Geçirilmesi Gerekenler" sheetId="3" r:id="rId3"/></sheets></workbook>},'xl/workbook.xml');Add($Z,q{<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Target="worksheets/sheet2.xml"/><Relationship Id="rId3" Target="worksheets/sheet3.xml"/></Relationships>},'xl/_rels/workbook.xml.rels');my@H=('Müşteri Adı','Müşteri Tipi','Servis Modeli','Katalog Referansı','Kırılım 3 (Service)','Kırılım 1 (Service Category)','Kırılım 2 (Support Team)');my$Model=$Bad?'Bilinmeyen':'Sabit Kapsam (Teklif Bazlı)';Add($Z,Sheet([\@H,[$CustomerA,'Perakende',$Model,'SRV-01','Windows İşletim Sistemi','Altyapı','Windows Ekibi'],[$CustomerB,'Banka','Unify Pack (Ticket Bazlı, Tüm Katalog)','SRV-02','Entra ID','Kimlik','Cloud Ekibi']]),'xl/worksheets/sheet1.xml');Add($Z,Sheet([['Müşteri'],[$CustomerA],[$CustomerB]]),'xl/worksheets/sheet2.xml');Add($Z,Sheet([['Konu'],['Lisanslama']]),'xl/worksheets/sheet3.xml');die'zip write failed'if$Z->writeToFileNamed($Path)!=AZ_OK;return$Path}
my$Path=Book(0);my$R=$Workbook->Inspect(Path=>$Path,IncludeRows=>1);ok($R->{Success},'valid workbook is ready');is($R->{Summary},{Mappings=>2,MappedCustomers=>2,ListedCustomers=>2,Services=>2,Categories=>2,SupportTeams=>2,ReviewRows=>1,Warnings=>0},'workbook summary is deterministic');is($R->{Mappings}->[0]->{CustomerKey},'panco','Turkish customer name becomes stable ASCII key');is($R->{Mappings}->[1]->{ServiceModel},'unify_pack','commercial model normalized');is($R->{Mappings}->[0]->{SupportTeam},'Windows Ekibi','support team remains an instance field');
my$Bad=$Workbook->Inspect(Path=>Book(1));ok(!$Bad->{Success},'unknown commercial model fails closed');is($Bad->{Warnings}->[0]->{Code},'SERVICE_MODEL_UNKNOWN','validation warning identifies unknown model');is($Workbook->Inspect(Path=>'missing.xlsx')->{Error},'FILE_NOT_FOUND','missing workbook rejected');
my$ImportPath=Book(0,lc$Helper->GetRandomID());my$ImportPreview=$Workbook->Inspect(Path=>$ImportPath,IncludeRows=>1);my@TenantKeys=map{'demo-'.$_->{CustomerKey}}@{$ImportPreview->{Mappings}};my$Import=$Kernel::OM->Get('Kernel::System::D724::CMDBWorkbookImport');my$Platform={ID=>'workbook-test',Roles=>['platform_admin'],TenantIDs=>['bootstrap']};is($Import->Apply(Path=>$ImportPath,UserID=>1,DemoData=>1,Subject=>$Platform)->{Error},'CONFIRMATION_REQUIRED','import requires explicit confirmation');is($Import->Apply(Path=>$ImportPath,UserID=>1,Confirm=>1,Subject=>$Platform)->{Error},'DEMO_DATA_ACKNOWLEDGEMENT_REQUIRED','import requires demo-data acknowledgement');my$Applied=$Import->Apply(Path=>$ImportPath,UserID=>1,Confirm=>1,DemoData=>1,Subject=>$Platform);diag(($Applied->{Error}//'unknown import error').':'.($Applied->{Reason}//q{}))if!$Applied->{Success};ok($Applied->{Success},'validated workbook imported into demo namespace');is($Applied->{Applied}->{Groups}->{Created}+$Applied->{Applied}->{Groups}->{Existing},2,'support groups are deduplicated before lookup');is($Applied->{Applied}->{Tenants}->{Created},2,'two demo tenants created');is($Applied->{Applied}->{Services}->{Created},2,'two tenant services created');is($Applied->{Applied}->{Instances}->{Created},2,'two service instances created');my$Replay=$Import->Apply(Path=>$ImportPath,UserID=>1,Confirm=>1,DemoData=>1,Subject=>$Platform);diag(($Replay->{Error}//'unknown replay error').':'.($Replay->{Reason}//q{}))if!$Replay->{Success};ok($Replay->{Success},'import replay succeeds');ok($Replay->{Idempotent},'second import is fully idempotent');is($Replay->{Applied}->{Groups}->{Existing},2,'replay reports unique existing support groups');my$DB=$Kernel::OM->Get('Kernel::System::DB');$DB->Prepare(SQL=>q{SELECT COUNT(*) FROM d724_tenant WHERE key_name IN (?,?) AND name LIKE '[DEMO] %'},Bind=>[\$TenantKeys[0],\$TenantKeys[1]]);my($DemoTenants)=$DB->FetchrowArray();is($DemoTenants,2,'all imported tenants are visibly labelled demo data');
done_testing;
