# --
# SPDX-License-Identifier: GPL-3.0-only
# --
use v5.24;use strict;use warnings;use Test2::V0;use Kernel::System::UnitTest::RegisterOM;
$Kernel::OM->ObjectParamAdd('Kernel::System::UnitTest::Helper'=>{RestoreDatabase=>1});my$H=$Kernel::OM->Get('Kernel::System::UnitTest::Helper');$H->ConfigSettingChange(Key=>'D724::CMDB::Enabled',Value=>1);$H->ConfigSettingChange(Key=>'D724::Catalog::Enabled',Value=>1);my$DB=$Kernel::OM->Get('Kernel::System::DB');for my$TenantID(qw(tenant-a tenant-b)){my@V=($TenantID,"Fixture $TenantID",1,1);my@B=map{\$_}@V;ok($DB->Do(SQL=>q{INSERT INTO d724_tenant (key_name,name,status,version,create_time,create_by,change_time,change_by) VALUES (?,?,'active',1,current_timestamp,?,current_timestamp,?)},Bind=>\@B),"$TenantID fixture created")}
my$C=$Kernel::OM->Get('Kernel::System::D724::CMDB');my$Catalog=$Kernel::OM->Get('Kernel::System::D724::Catalog');my$AdminA={ID=>'admin-a',Roles=>['tenant_admin'],TenantIDs=>['tenant-a']};my$AdminB={ID=>'admin-b',Roles=>['tenant_admin'],TenantIDs=>['tenant-b']};my$AgentA={ID=>'agent-a',Roles=>['agent'],TenantIDs=>['tenant-a']};my%BA=(Subject=>$AdminA,TenantID=>'tenant-a',UserID=>1);
my$S=$Catalog->ServiceCreate(%BA,Key=>'managed-os',Name=>'Managed Operating System',Status=>'active');ok($S->{Success},'catalog service created');my$Cat=$C->CategoryCreate(%BA,Key=>'infrastructure',Name=>'Infrastructure',Status=>'active');ok($Cat->{Success},'service category created');ok($C->ServiceCategorize(%BA,CategoryID=>$Cat->{Data}->{CategoryID},ServiceID=>$S->{Data}->{ServiceID})->{Success},'service assigned to category');
my$I=$C->InstanceCreate(%BA,ServiceID=>$S->{Data}->{ServiceID},Key=>'linux-prod',Name=>'Production Linux',ServiceModel=>'fixed_scope',Criticality=>'critical');ok($I->{Success},'service instance created');is($I->{Data}->{ServiceID},$S->{Data}->{ServiceID},'instance belongs to service');
my$T=$C->TypeCreate(%BA,Key=>'server',Name=>'Server',Status=>'active',AttributeSchema=>{version=>1,fields=>[{key=>'hostname',type=>'hostname',required=>1},{key=>'environment',type=>'select',required=>1,options=>['production','test']}]});ok($T->{Success},'CI type with validated schema created');my$CI=$C->CICreate(%BA,TypeID=>$T->{Data}->{TypeID},Key=>'srv-app-01',Name=>'Application Server',Status=>'active',Criticality=>'critical',Attributes=>{hostname=>'srv-app-01',environment=>'production'});ok($CI->{Success},'configuration item created');
my$B=$C->InstanceBindingCreate(%BA,ServiceInstanceID=>$I->{Data}->{ServiceInstanceID},CIID=>$CI->{Data}->{CIID},RelationshipType=>'supported_by');ok($B->{Success},'service instance bound to CI');is($C->InstanceBindingCreate(%BA,ServiceInstanceID=>$I->{Data}->{ServiceInstanceID},CIID=>$CI->{Data}->{CIID},RelationshipType=>'supported_by')->{IdempotentReplay},1,'binding replay is idempotent');my$G=$C->ServiceGraphGet(Subject=>$AgentA,TenantID=>'tenant-a',ServiceID=>$S->{Data}->{ServiceID});ok($G->{Success},'agent reads own-tenant service graph');is(scalar@{$G->{Data}->{Nodes}},1,'graph contains bound CI');
is($C->CIGet(Subject=>$AdminB,TenantID=>'tenant-a',CIID=>$CI->{Data}->{CIID})->{Error},'FORBIDDEN','cross-tenant read forbidden');is($C->CIGet(Subject=>$AdminA,TenantID=>'tenant-a',CIID=>999999)->{Error},'NOT_FOUND','unknown CI hidden');is($C->CIUpdate(%BA,CIID=>$CI->{Data}->{CIID},ExpectedVersion=>1,Name=>'Application Server Updated')->{Data}->{Version},2,'matching version updates CI');is($C->CIUpdate(%BA,CIID=>$CI->{Data}->{CIID},ExpectedVersion=>1,Name=>'Stale')->{Error},'VERSION_CONFLICT','stale CI write rejected');
is($C->CICreate(%BA,TypeID=>$T->{Data}->{TypeID},Key=>'bad-ci',Name=>'Bad CI',Attributes=>{environment=>'invalid',hostname=>'bad'})->{Error},'ATTRIBUTE_VALUE_INVALID','schema rejects invalid select value');
my$CI2=$C->CICreate(%BA,TypeID=>$T->{Data}->{TypeID},Key=>'srv-db-01',Name=>'Database Server',Status=>'active',Attributes=>{hostname=>'srv-db-01',environment=>'production'});my$R=$C->RelationCreate(%BA,SourceCIID=>$CI->{Data}->{CIID},TargetCIID=>$CI2->{Data}->{CIID},RelationType=>'depends_on');ok($R->{Success},'CI dependency created');is($C->RelationCreate(%BA,SourceCIID=>$CI2->{Data}->{CIID},TargetCIID=>$CI->{Data}->{CIID},RelationType=>'depends_on')->{Error},'RELATION_CYCLE','dependency cycle rejected');
my$Audit=$Kernel::OM->Get('Kernel::System::D724::Audit')->List(Subject=>$AdminA,TenantID=>'tenant-a',Limit=>100);ok($Audit->{Success},'CMDB mutations are auditable');ok(scalar(grep{($_->{Action}//q{})eq'cmdb.service_instance.created'}@{$Audit->{Data}}),'instance creation audit exists');ok($Kernel::OM->Get('Kernel::System::D724::Audit')->Verify(Subject=>$AdminA,TenantID=>'tenant-a')->{Valid},'audit chain verifies');
done_testing;
