# --
# CareOnCloud ESM enterprise service management platform.
# SPDX-License-Identifier: GPL-3.0-only
# --
package Kernel::Modules::AgentCareOnCloudProblem;
use v5.24;use strict;use warnings;our$ObjectManagerDisabled=1;
sub new{my($T,%P)=@_;return bless{%P},$T}
sub Run{my($S,%P)=@_;my$L=$Kernel::OM->Get('Kernel::Output::HTML::Layout');my$W=$Kernel::OM->Get('Kernel::System::Web::Request');my$D=$Kernel::OM->Get('Kernel::System::CareOnCloud::TenantDirectory');my$G=$Kernel::OM->Get('Kernel::System::CareOnCloud::TenantGuard');my$O=$Kernel::OM->Get('Kernel::System::CareOnCloud::Problem');my$Ctx=$D->ContextGet(UserID=>$S->{UserID});return$L->NoPermission(WithHeader=>'yes')if!$Ctx->{Success};my$Sub=$Ctx->{Subject};my@T=grep{$G->DecisionGet(Subject=>$Sub,Resource=>{TenantID=>$_},Action=>'case.read')->{Allowed}}@{$Sub->{TenantIDs}};return$L->NoPermission(WithHeader=>'yes')if!@T;my%Own=map{$_=>1}@T;my$Tenant=$W->GetParam(Param=>'TenantID')//$T[0];return$L->NoPermission(WithHeader=>'yes')if!$Own{$Tenant};
 my$A=$S->{Subaction}//q{};if($A){$L->ChallengeTokenCheck();my%X=(Subject=>$Sub,TenantID=>$Tenant,UserID=>$S->{UserID});my$R;if($A eq'Create'){$R=$O->Create(%X,map{$_=>$W->GetParam(Param=>$_)}qw(Title Symptom BusinessImpact Category Impact Urgency))}elsif($A eq'Start'){$R=$O->Start(%X,ProblemID=>$W->GetParam(Param=>'ProblemID'),ExpectedVersion=>$W->GetParam(Param=>'ExpectedVersion'))}elsif($A eq'Diagnose'){$R=$O->Diagnose(%X,ProblemID=>$W->GetParam(Param=>'ProblemID'),ExpectedVersion=>$W->GetParam(Param=>'ExpectedVersion'),RootCause=>$W->GetParam(Param=>'RootCause'),Workaround=>$W->GetParam(Param=>'Workaround'))}elsif($A eq'KnownError'){$R=$O->PublishKnownError(%X,ProblemID=>$W->GetParam(Param=>'ProblemID'),ExpectedVersion=>$W->GetParam(Param=>'ExpectedVersion'))}elsif($A eq'Resolve'){$R=$O->Resolve(%X,ProblemID=>$W->GetParam(Param=>'ProblemID'),ExpectedVersion=>$W->GetParam(Param=>'ExpectedVersion'),PermanentFix=>$W->GetParam(Param=>'PermanentFix'))}elsif($A eq'Close'){$R=$O->Close(%X,ProblemID=>$W->GetParam(Param=>'ProblemID'),ExpectedVersion=>$W->GetParam(Param=>'ExpectedVersion'))}elsif($A eq'Reopen'){$R=$O->Reopen(%X,ProblemID=>$W->GetParam(Param=>'ProblemID'),ExpectedVersion=>$W->GetParam(Param=>'ExpectedVersion'))}else{$R={Success=>0,Error=>'ACTION_INVALID'}}return$L->Redirect(OP=>"Action=AgentCareOnCloudProblem;TenantID=$Tenant")if$R->{Success};$P{Error}=$R->{Error}}
 for my$I(@T){$L->Block(Name=>'TenantOption',Data=>{TenantID=>$I,Selected=>$I eq$Tenant?'selected':q{}})}my$Manage=$G->DecisionGet(Subject=>$Sub,Resource=>{TenantID=>$Tenant},Action=>'case.delete')->{Allowed}?1:0;my$List=$O->List(Subject=>$Sub,TenantID=>$Tenant,UserID=>$S->{UserID});return$L->NoPermission(WithHeader=>'yes')if!$List->{Success};my%N;for my$R(@{$List->{Data}}){$N{$R->{Status}}++;$L->Block(Name=>'ProblemRow',Data=>$R);$L->Block(Name=>'StartAction',Data=>$R)if$R->{Status}eq'draft';if($R->{Status}=~m{\A(?:investigating|known_error)\z}){$L->Block(Name=>'DiagnosisAction',Data=>$R);$L->Block(Name=>'ResolveAction',Data=>$R)}$L->Block(Name=>'KnownErrorAction',Data=>$R)if$R->{Status}eq'investigating'&&length($R->{RootCause})&&length($R->{Workaround});$L->Block(Name=>'CloseAction',Data=>$R)if$Manage&&$R->{Status}eq'resolved';$L->Block(Name=>'ReopenAction',Data=>$R)if$Manage&&$R->{Status}eq'closed'}
 my$Out=$L->Header(Title=>'CareOnCloud Problem Management');$Out.=$L->NavigationBar();$Out.=$L->Notify(Priority=>'Error',Info=>$P{Error})if$P{Error};$Out.=$L->Output(TemplateFile=>'AgentCareOnCloudProblem',Data=>{TenantID=>$Tenant,Total=>scalar@{$List->{Data}},Investigating=>$N{investigating}//0,KnownErrors=>$N{known_error}//0,Resolved=>$N{resolved}//0});$Out.=$L->Footer();return$Out}
1;
