# --
# SPDX-License-Identifier: GPL-3.0-only
# --
package Kernel::System::D724::CMDBWorkbookImport;
use v5.24;use strict;use warnings;use utf8;
our $VERSION='0.3.4';
our @ObjectDependencies=('Kernel::System::D724::Catalog','Kernel::System::D724::CMDB','Kernel::System::D724::CMDBWorkbook','Kernel::System::D724::TenantDirectory','Kernel::System::DB','Kernel::System::Group','Kernel::System::Log');
sub new{return bless{},$_[0]}
sub Apply{
 my($S,%P)=@_;return$S->_E('CONFIRMATION_REQUIRED')if!$P{Confirm};return$S->_E('DEMO_DATA_ACKNOWLEDGEMENT_REQUIRED')if!$P{DemoData};return$S->_E('USER_ID_INVALID')if($P{UserID}//q{})!~m{\A[1-9][0-9]*\z};my$Subject=$P{Subject};return$S->_E('PLATFORM_ADMIN_REQUIRED')if ref$Subject ne'HASH'||ref$Subject->{Roles}ne'ARRAY'||!grep{$_ eq'platform_admin'}@{$Subject->{Roles}};
 my$Preview=$Kernel::OM->Get('Kernel::System::D724::CMDBWorkbook')->Inspect(Path=>$P{Path},IncludeRows=>1);return$Preview if!$Preview->{Success};my(%Work,%Customer);for my$R(@{$Preview->{Mappings}}){my$Tenant='demo-'.$R->{CustomerKey};$Tenant=substr($Tenant,0,127);$Tenant=~s{-+\z}{};$Customer{$Tenant}=$R->{Customer};my$K="$Tenant|$R->{ServiceKey}";if(my$Old=$Work{$K}){for my$F(qw(CategoryKey Category ServiceModel SupportTeam Service)){return$S->_E('MAPPING_CONFLICT',"rows $Old->{Row} and $R->{Row}: $F")if($Old->{$F}//q{})ne($R->{$F}//q{})}next}$Work{$K}={%$R,TenantID=>$Tenant,InstanceKey=>$S->_InstanceKey($R->{ServiceKey})}}
 return$S->_Apply(Subject=>$Subject,UserID=>$P{UserID},Work=>\%Work,Customer=>\%Customer,Preview=>$Preview);
}
sub _Apply{
 my($S,%P)=@_;my$Directory=$Kernel::OM->Get('Kernel::System::D724::TenantDirectory');my$Catalog=$Kernel::OM->Get('Kernel::System::D724::Catalog');my$CMDB=$Kernel::OM->Get('Kernel::System::D724::CMDB');my$Group=$Kernel::OM->Get('Kernel::System::Group');my%Count=map{$_=>{Created=>0,Existing=>0}}qw(Groups Tenants Memberships Categories Services Categorizations Instances);my(%GroupID,%Category,%Service,%Instance);
 my%Team=map{($_->{SupportTeam}//q{})=>1}values%{$P{Work}};delete$Team{q{}};for my$Team(sort keys%Team){my$Name='careon-demo-'.$Kernel::OM->Get('Kernel::System::D724::CMDBWorkbook')->_Key($Team);my$ID=$Group->GroupLookup(Group=>$Name);if($ID){$Count{Groups}->{Existing}++}else{$ID=$Group->GroupAdd(Name=>$Name,Comment=>"[DEMO] Workbook support team: $Team",ValidID=>1,UserID=>$P{UserID});return$S->_E('GROUP_CREATE_FAILED',$Name)if!$ID;$Count{Groups}->{Created}++}$GroupID{$Team}=$ID}
 for my$Tenant(sort keys%{$P{Customer}}){my$Name='[DEMO] '.$P{Customer}->{$Tenant};my$Existing=$S->_TenantRow($Tenant);if($Existing){return$S->_E('DEMO_TENANT_COLLISION',$Tenant)if$Existing->{Name}ne$Name;$Count{Tenants}->{Existing}++}else{my$R=$Directory->TenantCreate(Subject=>$P{Subject},TenantID=>$Tenant,Name=>$Name,UserID=>$P{UserID});return$S->_E($R->{Error}//'TENANT_CREATE_FAILED',"tenant:$Tenant")if!$R->{Success};$Count{Tenants}->{Created}++}my$M=$S->_MembershipRow($Tenant,$P{UserID},'tenant_admin');if($M){$Count{Memberships}->{Existing}++}else{my$R=$Directory->MembershipGrant(Subject=>$P{Subject},TenantID=>$Tenant,MemberUserID=>$P{UserID},Role=>'tenant_admin',UserID=>$P{UserID});return$S->_E($R->{Error}//'MEMBERSHIP_CREATE_FAILED',"membership:$Tenant")if!$R->{Success};$Count{Memberships}->{Created}++}}
 for my$K(sort keys%{$P{Work}}){my$W=$P{Work}->{$K};my%Base=(Subject=>$P{Subject},TenantID=>$W->{TenantID},UserID=>$P{UserID});my$CK="$W->{TenantID}|$W->{CategoryKey}";if(!$Category{$CK}){my$L=$CMDB->CategoryList(%Base);return$L if!$L->{Success};my($E)=grep{$_->{Key}eq$W->{CategoryKey}}@{$L->{Data}};if($E){$Category{$CK}=$E;$Count{Categories}->{Existing}++}else{my$R=$CMDB->CategoryCreate(%Base,Key=>$W->{CategoryKey},Name=>$W->{Category},Description=>'[DEMO] Workbook import',Status=>'active');return$R if!$R->{Success};$Category{$CK}=$R->{Data};$Count{Categories}->{Created}++}}
  my$SK="$W->{TenantID}|$W->{ServiceKey}";if(!$Service{$SK}){my$L=$Catalog->ServiceList(%Base);return$L if!$L->{Success};my($E)=grep{$_->{Key}eq$W->{ServiceKey}}@{$L->{Data}};if($E){return$S->_E('DEMO_SERVICE_COLLISION',$SK)if$E->{Name}ne$W->{Service};$Service{$SK}=$E;$Count{Services}->{Existing}++}else{my$R=$Catalog->ServiceCreate(%Base,Key=>$W->{ServiceKey},Name=>$W->{Service},Description=>'[DEMO] Workbook import',Status=>'active');return$R if!$R->{Success};$Service{$SK}=$R->{Data};$Count{Services}->{Created}++}}
  my$Link=$CMDB->ServiceCategorize(%Base,CategoryID=>$Category{$CK}->{CategoryID},ServiceID=>$Service{$SK}->{ServiceID});return$Link if!$Link->{Success};$Count{Categorizations}->{$Link->{IdempotentReplay}?'Existing':'Created'}++;
  my$IK="$W->{TenantID}|$W->{InstanceKey}";if(!$Instance{$IK}){my$L=$CMDB->InstanceList(%Base,ServiceID=>$Service{$SK}->{ServiceID});return$L if!$L->{Success};my($E)=grep{$_->{Key}eq$W->{InstanceKey}}@{$L->{Data}};my$G=length($W->{SupportTeam})?$GroupID{$W->{SupportTeam}}:undef;if($E){return$S->_E('DEMO_INSTANCE_COLLISION',$IK)if$E->{ServiceModel}ne$W->{ServiceModel}||($E->{SupportGroupID}//0)!=($G//0);$Instance{$IK}=$E;$Count{Instances}->{Existing}++}else{my$R=$CMDB->InstanceCreate(%Base,ServiceID=>$Service{$SK}->{ServiceID},Key=>$W->{InstanceKey},Name=>'[DEMO] '.$W->{Service},Description=>'Workbook row '.$W->{Row},SupportGroupID=>$G,ServiceModel=>$W->{ServiceModel},Status=>'active',Criticality=>'medium');return$R if!$R->{Success};$Instance{$IK}=$R->{Data};$Count{Instances}->{Created}++}}
 }
 my$Created=0;$Created+=$Count{$_}->{Created}for keys%Count;return{Success=>1,DemoData=>1,Idempotent=>$Created?0:1,Summary=>$P{Preview}->{Summary},Applied=>\%Count}
}
sub _TenantRow{my($S,$T)=@_;my$DB=$Kernel::OM->Get('Kernel::System::DB');$DB->Prepare(SQL=>'SELECT key_name,name,status,version FROM d724_tenant WHERE key_name=?',Bind=>[\$T],Limit=>1);my@R=$DB->FetchrowArray();return@R?{TenantID=>$R[0],Name=>$R[1],Status=>$R[2],Version=>0+$R[3]}:undef}
sub _MembershipRow{my($S,$T,$U,$Role)=@_;my$DB=$Kernel::OM->Get('Kernel::System::DB');$DB->Prepare(SQL=>"SELECT id FROM d724_tenant_agent_role WHERE tenant_id=? AND user_id=? AND role_name=? AND status='active'",Bind=>[\$T,\$U,\$Role],Limit=>1);my($ID)=$DB->FetchrowArray();return$ID}
sub _InstanceKey{my($S,$K)=@_;$K='instance-'.$K;$K=substr($K,0,100);$K=~s{-+\z}{};return$K}
sub _E{my($S,$E,$R)=@_;return{Success=>0,Error=>$E,Reason=>$R//$E}}
1;
