# --
# SPDX-License-Identifier: GPL-3.0-only
# --
package Kernel::System::D724::CMDBWorkbook;
use v5.24;use strict;use warnings;use utf8;
use Archive::Zip qw(AZ_OK);use XML::LibXML;
our $VERSION='0.2.2';our @ObjectDependencies=();
my @Header=('Müşteri Adı','Müşteri Tipi','Servis Modeli','Katalog Referansı','Kırılım 3 (Service)','Kırılım 1 (Service Category)','Kırılım 2 (Support Team)');
my %Model=('Sabit Kapsam (Teklif Bazlı)'=>'fixed_scope','Unify Pack (Ticket Bazlı, Tüm Katalog)'=>'unify_pack','Unify Pack (Ticket Bazlı, Kota Dahilinde Tüm Katalog)'=>'unify_pack');
sub new{return bless{},$_[0]}
sub Inspect{
 my($S,%P)=@_;my$Path=$P{Path}//q{};return{Success=>0,Error=>'FILE_NOT_FOUND'}if!-f$Path;my$Book=$S->_Read(Path=>$Path);return$Book if!$Book->{Success};
 my$Rows=$Book->{Sheets}->{'Müşteri-Servis Eşleme'};return{Success=>0,Error=>'MAPPING_SHEET_MISSING'}if!$Rows;my$Header=shift@$Rows;for my$I(0..$#Header){return{Success=>0,Error=>'MAPPING_HEADER_INVALID',Column=>$I+1,Expected=>$Header[$I],Actual=>$Header->[$I]//q{}}if($Header->[$I]//q{})ne$Header[$I]}
 my(@Mappings,@Warnings,%Customers,%Services,%Categories,%Teams,%Models);my$RowNo=1;for my$R(@$Rows){$RowNo++;next if!grep{length($_//q{})}@$R;my($Customer,$CustomerType,$ModelName,$Reference,$Service,$Category,$Team)=map{$S->_Trim($_)}@$R[0..6];my@Missing;push@Missing,$Header[$_]for grep{!length($S->_Trim($R->[$_]))}(0,2,4,5);if(@Missing){push@Warnings,{Code=>'REQUIRED_VALUE_MISSING',Sheet=>'Müşteri-Servis Eşleme',Row=>$RowNo,Fields=>\@Missing};next}my$ServiceModel=$Model{$ModelName};if(!$ServiceModel){push@Warnings,{Code=>'SERVICE_MODEL_UNKNOWN',Sheet=>'Müşteri-Servis Eşleme',Row=>$RowNo,Value=>$ModelName};next}push@Mappings,{Row=>$RowNo,Customer=>$Customer,CustomerKey=>$S->_Key($Customer),CustomerType=>$CustomerType,ServiceModel=>$ServiceModel,CatalogReference=>$Reference,Service=>$Service,ServiceKey=>$S->_Key(length$Reference?$Reference:$Service),Category=>$Category,CategoryKey=>$S->_Key($Category),SupportTeam=>$Team};$Customers{$Customer}=1;$Services{$Service}=1;$Categories{$Category}=1;$Teams{$Team}=1 if length$Team;$Models{$ServiceModel}=1}
 my$Review=$Book->{Sheets}->{'Gözden Geçirilmesi Gerekenler'}//[];my@ReviewData=@$Review;shift@ReviewData if@ReviewData;my$ReviewCount=scalar grep{grep{length($_//q{})}@$_}@ReviewData;my$CustomerRows=$Book->{Sheets}->{'Müşteriler'}//[];my$Listed=@$CustomerRows?scalar(@$CustomerRows)-1:0;my$R={Success=>@Warnings?0:1,ReadyToApply=>@Warnings?0:1,Source=>{Path=>$Path,Sheets=>[sort keys%{$Book->{Sheets}}]},Summary=>{Mappings=>scalar@Mappings,MappedCustomers=>scalar keys%Customers,ListedCustomers=>$Listed,Services=>scalar keys%Services,Categories=>scalar keys%Categories,SupportTeams=>scalar keys%Teams,ReviewRows=>$ReviewCount,Warnings=>scalar@Warnings},ServiceModels=>[sort keys%Models],Warnings=>\@Warnings};$R->{Mappings}=\@Mappings if$P{IncludeRows};return$R
}
sub _Read{
 my($S,%P)=@_;my$Zip=Archive::Zip->new();return{Success=>0,Error=>'XLSX_OPEN_FAILED'}if$Zip->read($P{Path})!=AZ_OK;my$Parser=XML::LibXML->new();$Parser->no_network(1);$Parser->recover(0);my$Shared=[];if($Zip->memberNamed('xl/sharedStrings.xml')){my$XML=$Zip->contents('xl/sharedStrings.xml');my$D=eval{$Parser->load_xml(string=>$XML)};return{Success=>0,Error=>'XLSX_XML_INVALID',Part=>'sharedStrings'}if!$D;for my$SI($D->findnodes('//*[local-name()="si"]')){push@$Shared,join q{},map{$_->textContent}$SI->findnodes('.//*[local-name()="t"]')}}my$WorkbookXML=$Zip->contents('xl/workbook.xml');my$RelationsXML=$Zip->contents('xl/_rels/workbook.xml.rels');my$WB=eval{$Parser->load_xml(string=>$WorkbookXML)};my$Rel=eval{$Parser->load_xml(string=>$RelationsXML)};return{Success=>0,Error=>'XLSX_STRUCTURE_INVALID'}if!$WB||!$Rel;my%Target=map{($_->getAttribute('Id')=>$_->getAttribute('Target'))}$Rel->findnodes('//*[local-name()="Relationship"]');my%Sheets;for my$Node($WB->findnodes('//*[local-name()="sheet"]')){my$Name=$Node->getAttribute('name');my$RID=$Node->getAttributeNS('http://schemas.openxmlformats.org/officeDocument/2006/relationships','id');my$Target=$Target{$RID}//next;$Target="xl/$Target"if$Target!~m{\Axl/};$Target=~s{xl/worksheets/\.\./}{xl/};my$XML=$Zip->contents($Target);next if!defined$XML;my$D=eval{$Parser->load_xml(string=>$XML)};return{Success=>0,Error=>'XLSX_XML_INVALID',Part=>$Target}if!$D;my@Rows;for my$Row($D->findnodes('//*[local-name()="sheetData"]/*[local-name()="row"]')){my@Values;for my$Cell($Row->findnodes('./*[local-name()="c"]')){my($Letters)=($Cell->getAttribute('r')//q{})=~m{\A([A-Z]+)};next if!$Letters;my$Col=0;$Col=$Col*26+ord($_)-64 for split//,$Letters;my$Type=$Cell->getAttribute('t')//q{};my($V)=$Cell->findnodes('./*[local-name()="v"]');my$Value=$V?$V->textContent:q{};$Value=$Shared->[$Value]//q{}if$Type eq's';$Value=join q{},map{$_->textContent}$Cell->findnodes('.//*[local-name()="t"]')if$Type eq'inlineStr';$Values[$Col-1]=$Value}push@Rows,\@Values}$Sheets{$Name}=\@Rows}return{Success=>1,Sheets=>\%Sheets}
}
sub _Trim{my($S,$V)=@_;$V//=q{};$V=~s{\A\s+|\s+\z}{}g;return$V}
sub _Key{my($S,$V)=@_;$V=lc$S->_Trim($V);my%M=('ç'=>'c','ğ'=>'g','ı'=>'i','ö'=>'o','ş'=>'s','ü'=>'u');$V=~s{([çğıöşü])}{$M{$1}}ge;$V=~s{[^a-z0-9]+}{-}g;$V=~s{\A-+|-+\z}{}g;$V=substr($V,0,100);$V=~s{-+\z}{};return length$V>1?$V:'item'}
1;
